TYPO3-Console/TYPO3-Console

Classes/Hook/ExtensionInstallation.php, ext_localconf.php
=> [FEATURE] Automatically create _cli_lowlevel BE user

Classes/Exception.php
=> [BUGFIX] Fix service base exception

Tests/Unit/Parser/Fixtures/NamespacedClassFixture.php, Tests/Unit/Parser/Fixtures/NamespacedInterfaceFixture.php, Tests/Unit/Parser/PhpParserTest.php, Tests/Unit/Service/CacheServiceTest.php
=> [TASK] Fix namespace of unit tests

Classes/Command/DatabaseCommandController.php
Is this what you intended on saying? Just wasn't worded clearly before.
=> [DOC] Fixing grammer

Classes/Command/InstallCommandController.php
=> Catch PackageManager exception while deactivating packages

Classes/Service/Database/Schema/SchemaService.php
=> [BUGFIX] Do not change current value on DB schema updates (1.1.x)

Classes/Service/Database/Schema/SchemaService.php
=> [BUGFIX] Do not change current value on DB schema updates (1.2.x)

.travis.yml
* Add test for create package states command
* Remove env config, which is currently done in travis repo settings
=> Cleanup and extend travis.yml

Classes/Mvc/Cli/RequestHandler.php
=> [FEATURE] Make help the default command

Classes/Command/BackendCommandController.php
=> [FEATURE] Lock backend for editors

.travis.yml
Grep natively supports inversion of pattern matching.
=> [TASK] Simplify test for configuration:remove

Classes/Hook/ExtensionInstallation.php
=> When backend user "_cli_lowlevel" was deleted, no new user is created

Classes/Command/HelpCommandController.php
This gets us closer to other Symfony console applications.
=> [TASK] Reformat and colorize help output

Classes/Command/BackendCommandController.php, Classes/Command/CacheCommandController.php, Classes/Command/CleanupCommandController.php, Classes/Command/ConfigurationCommandController.php, Classes/Command/DatabaseCommandController.php, Classes/Command/ExtensionCommandController.php, Classes/Command/FrontendCommandController.php, Classes/Command/HelpCommandController.php, Classes/Command/InstallCommandController.php, Classes/Command/SchedulerCommandController.php
=> [DOC] Document command controllers and arguments

Classes/Command/BackendCommandController.php
Add warning, error and info tags consistently in BackendCommandController
=> [TASK] Streamline output formatting

composer.json
Make sure we define a clear upper bound.
=> [BUGFIX] Fix symfony/console dependency

Documentation/CommandReference/Index.rst, Documentation/Index.rst
=> [TASK] Add generated command index

Classes/Command/DatabaseCommandController.php, Classes/Command/DocumentationCommandController.php
=> [BUGFIX] Revert to plain echo for outputting raw text

Classes/Core/Booting/Scripts.php, Classes/Core/ConsoleBootstrap.php, Classes/Error/ErrorHandler.php, Classes/Error/ExceptionHandler.php
I don't regularly see exception messages,
but if I do, they are beautiful.
At the same time, the error and exception handler code
should be beautiful as well.
=> [FEATURE] Streamline and beautify exception output

Classes/Core/Booting/Scripts.php, Classes/Core/ConsoleBootstrap.php, Scripts/typo3cms.php, ext_localconf.php
Add preliminary code to work also from vendor dir.
Clarify code paths in comments
=> [TASK] Make entry script more flexible

Scripts/typo3cms
=> [BUGFIX] Fix binary for non composer mode

.gitattributes, Configuration/Console/Commands.php, Documentation/CommandReference/Index.rst, Resources/Private/CommandReference/Templates/CommandReferenceTemplate.txt, Resources/Private/CommandReference/src/Command/CommandReferenceCommandController.php, Resources/Private/CommandReference/src/ViewHelpers/Format/IndentViewHelper.php, Resources/Private/CommandReference/src/ViewHelpers/Format/UnderlineViewHelper.php, composer.json
Exclude everything for production use though
=> [FEATURE] Add console documentation rendering command

.travis.yml, Classes/Command/HelpCommandController.php, Classes/Composer/InstallerScripts.php
Also remove unreachable code in help command
=> [BUGFIX] Fix version number output in help message

Classes/Command/ExtensionCommandController.php, Classes/Command/HelpCommandController.php, Documentation/Settings.yml, Resources/Private/ExtensionArtifacts/ext_emconf.php, composer.json, ext_emconf.php
The command had no implementation any more and caused a recursion.
Add the implementation again and fix the command references
for the deprecated commands.
=> [BUGFIX] Fix dumpautoload command

Classes/Mvc/Cli/CommandDispatcher.php
Symfony process is much more robust an reliable
than just using exec. Make use of it.
=> [TASK] Use Symfony process to spawn processes

Classes/Core/ConsoleBootstrap.php, Classes/Install/CliSetupRequestHandler.php, Classes/Package/UncachedPackageManager.php
Re-create autoload files in non composer mode if needed.
Simplify auto-activation logic
Fixes #300
=> [BUGFIX] Make sure classes are available in non composer mode

Classes/Command/InstallCommandController.php
TYPO3 cannot reliably install if this file exists. There are
way to many checks for that file, so that if it exists,
executing installation code will lead to unpredictable results.
Therefore we now abort the installation in non interactive mode
and offer the deletion of this file in interactive mode.
Fixes #282
=> [BUGFIX] Abort installation if LocalConfiguration.php exists

.travis.yml, composer.json
Allow installation of TYPO3 8.0 to 8.2 again and add
builds for these versions
=> [BUGFIX] Fix TYPO3 dependency in composer.json

Classes/Command/HelpCommandController.php, Documentation/Settings.yml, Resources/Private/ExtensionArtifacts/ext_emconf.php
Revert accidental dowgrade of version
This reverts commit cc8c8604ccc6402af2aa9fb75c4af5b6eaedaa29.
=> Revert "Release 3.5.0"

.travis.yml, Classes/Command/DatabaseCommandController.php, Classes/Service/Database/SchemaService.php, Documentation/CommandReference/Index.rst
Add possibiltiy to review possible database updates
before actually performing them
=> [FEATURE] Add --dry-run support for database:updateschema

README.md
=> [TASK] Fix README.md typo

Classes/Database/Process/MysqlCommand.php
=> [TASK] Use unlimited timeout for DB export/import

.travis.yml, Classes/Command/DatabaseCommandController.php, Documentation/CommandReference/Index.rst
This allows for passing a list of tables to exclude from the database export.
=> [FEATURE] Add "--excluded-tables" argument to "database:export"

.travis.yml, Classes/Command/BackendCommandController.php, appveyor.yml
=> Make backend lock and unlock idempotent

.travis.yml, Scripts/typo3cms, Scripts/typo3cms.php, appveyor.yml
Remove the complicated nested if construct with a "simple"
if else that covers all cases we have (composer, extension, root package)
=> [TASK] Streamline entry script

.travis.yml, Classes/Command/HelpCommandController.php, Classes/Core/Booting/Scripts.php
This makes it possible to exit with an error code, so that
it is clear that an error happend
=> [BUGFIX] Use error command in our HelpCommandController

Classes/Core/ConsoleBootstrap.php
Resolves: #481
Releases: master
=> [BUGFIX] Initialize also runtime activated packages

Classes/Command/ConfigurationCommandController.php, Classes/Service/Configuration/ConsoleRenderer/ConsoleRenderer.php, Documentation/CommandReference/Index.rst, Tests/Functional/Command/ConfigurationCommandControllerTest.php
=> [FEATURE] Add option --json to configuration commands

Classes/Service/CacheService.php
With https://github.com/TYPO3/TYPO3.CMS/commit/d9982119c891e59e10398ccfcf8d220f64245722
A TYPO3 bug was fixed, which we need to fix as well.
=> [BUGFIX] Apply TYPO3 core fix to our cache service code

Classes/Command/ConfigurationCommandController.php, Classes/Service/Configuration/ConsoleRenderer/ConsoleRenderer.php, Configuration/Console/Commands.php, Tests/Functional/Command/ConfigurationCommandControllerTest.php
Otherwise we get strange results e.g. for caching config.
=> [BUGFIX] Use full bootstrap for configuration:show command

Classes/Command/InstallCommandController.php, Classes/Install/CliSetupRequestHandler.php, Documentation/CommandReference/Index.rst
=> [BUGFIX] Do not allow "dist" as setup type in composer mode

Classes/Command/FrontendCommandController.php, composer.json
* Simplify makeAbsolute
* Remove wrong class comment
* Remove not needed imports
=> Clean up FrontendCommandController

Classes/Command/UpgradeCommandController.php, Classes/Composer/InstallerScripts.php, Classes/Core/ConsoleBootstrap.php, Classes/Install/CliSetupRequestHandler.php
Install tool code was changed and now returns flash messages
instead of status messages, so we need to be aware of that.
Furthermore we must not call removed methods
=> [FEATURE] Compatiblity with current TYPO3 master

Classes/Command/UpgradeCommandController.php, Classes/Core/ConsoleBootstrap.php
Do not call setCacheHashOptions in bootstrap
for TYPO3 9
=> [BUGFIX] TYPO3 master compatibiltiy

Classes/Command/DatabaseCommandController.php, Classes/Database/Schema/SchemaUpdateResult.php, Classes/Database/Schema/SchemaUpdateResultRenderer.php, Classes/Service/Database/SchemaService.php, Tests/Functional/Command/DatabaseCommandControllerTest.php, Tests/Functional/Fixtures/Extensions/ext_broken_sql/ext_emconf.php, Tests/Functional/Fixtures/Extensions/ext_broken_sql/ext_tables.sql
=> [BUGFIX] Output error messages on schema update

Classes/Mvc/Cli/Symfony/Application.php, Classes/Mvc/Cli/Symfony/Command/HelpCommand.php, Classes/Mvc/Cli/Symfony/Command/ListCommand.php, Classes/Mvc/Cli/Symfony/Descriptor/TextDescriptor.php
Deal with longer description texts in a nicer
and better readable way.
We may contribute this back to Symfony upstream
at some point
=> Improve Symfony descriptor output

Classes/Command/CacheCommandController.php, Classes/Command/HelpCommandController.php, Classes/Mvc/Cli/Command.php, Classes/Mvc/Cli/CommandArgumentDefinition.php, Classes/Mvc/Cli/Symfony/Command/CommandControllerCommand.php, Tests/Functional/Command/CacheCommandControllerTest.php
Use this synopsis in all relevant places
=> [FEATURE] Provide synopsis for command controller commands

.travis.yml
* Have dedicated builds for lint and consistency
* Don't composer install for those
=> Restructure Travis builds

Classes/Command/CleanupCommandController.php, Classes/Command/SchedulerCommandController.php, Classes/Core/Booting/RunLevel.php, Classes/Core/Booting/Scripts.php, Classes/Core/Cache/FakeDatabaseBackend.php, Classes/Install/Upgrade/UpgradeHandling.php, Scripts/typo3console.php
When executing a single task and that fails, we
let the exception bubble up.
=> [BUGFIX] Don't silently catch exception for single tasks

.travis.yml
See https://docs.travis-ci.com/user/conditional-builds-stages-jobs
=> [TASK] Limit publish build stage to tags

Classes/Command/CacheCommandController.php
To flush caches, we need to know which caches exist.
In TYPO3 extensions can provide their own caches in ext_localconf.php
So we need to load these files to be able to flush all caches.
However two introduced changes in TYPO3 hinder us to do so.
1. Exceptions are thrown when extension configuration does not exist.
The new extension configuration API in TYPO3 9.0 throws exceptions
and is used in ext_localconf.php files in core extensions.
Therefore it is never possible to load these files without having
a LocalConfiguration.php present, which contains such configuration.
2. Loading TCA now requires a database connection
Since we also load TCA in the same booting step with including
ext_localconf.php files, flushing caches will always fail,
when no database connection is configured (no …
=> [BUGFIX] Gracefully exit when flushing file caches in pre-install state

Classes/Core/Kernel.php, Classes/Mvc/Cli/CommandCollection.php, Resources/Private/ExtensionArtifacts/ext_emconf.php
* Initialize class loader earlier
* Include config if extension is not active
* Fix dependencies in ext_emconf.php
=> [BUGFIX] Fix non composer mode

Classes/Install/Upgrade/UpgradeHandling.php, Classes/Mvc/Cli/CommandDispatcher.php
The previously introduced fixes simplified the code already,
but we can get it more comprehensive, by extracting to methods
and simplify the if elseif else constructs into a simple if else.
=> [TASK] Refactor CommandDispatcher

Classes/Composer/InstallerScript/InstallDummyExtension.php, Classes/Install/Upgrade/UpgradeHandling.php
Mention "console" early to make clear where this message comes from.
=> [TASK] Clarify dummy extension warning

Classes/Console/Command/DatabaseCommandController.php, Classes/Console/Database/Configuration/ConnectionConfiguration.php, Classes/Console/Database/Process/MysqlCommand.php, Configuration/Console/Commands.php, Documentation/CommandReference/Index.rst
* Quit with error when no MySQL connections are found.
* Dump tables of all found MySQL connections
=> [BUGFIX] Improve handling of configured db connections

.travis.yml, Classes/Console/Install/Upgrade/UpgradeWizardExecutor.php, Classes/Console/Install/Upgrade/UpgradeWizardFactory.php, Classes/Console/Install/Upgrade/UpgradeWizardList.php, Classes/Console/Mvc/Cli/CommandDispatcher.php, Configuration/Console/Commands.php, Packages/CreateReferenceCommand/src/Command/CommandReferenceRenderCommand.php, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php, appveyor.yml, composer.json
Temporary work-around until upgrade wizards are fully
implemented in core.
@todo might be necessary to check interface existence before checking
implementations.
=> [TASK] Make console compatible with master

Classes/Console/Mvc/Cli/CommandDispatcher.php
In order to not interfere with the actual output
of sub-processes, we suppress the native php error output
for starting a sub-process.
Any important error will be turned into an exception anyway,
which will result in the sub-process to fail.
Fixes: #751
=> [BUGFIX] Suppress error output for sub-processes

Classes/Console/Command/InstallCommandController.php, Classes/Console/Install/Action/InstallActionDispatcher.php, Classes/Console/Install/Action/WriteWebServerConfigAction.php, Configuration/Install/InstallSteps.yaml, Documentation/CommandReference/Index.rst, Resources/Private/Compatibility/TYPO3v87/FolderStructureTemplateFiles/root-htaccess, Resources/Private/Compatibility/TYPO3v87/FolderStructureTemplateFiles/root-web-config, Tests/Console/Functional/Command/Install/InstallCommandControllerTest.php, phpunit.xml.dist
A new install step is added to the install:setup command,
which asks for creation of a web server config file.
Fixes: #756
=> [FEATURE] Create web server config file upon installation

Classes/Console/Command/DatabaseCommandController.php, Classes/Console/Command/InstallCommandController.php, Documentation/CommandReference/Index.rst
* Document environment variables for install:setup
* Clarify database:updateschema
Fixes: #736
Fixes: #758
=> [BUGFIX] Improve documentation

Classes/Console/Mvc/Cli/Symfony/Descriptor/TextDescriptor.php
=> [BUGFIX] Handle commands without description

Classes/Console/Command/FrontendCommandController.php, Documentation/Index.rst, README.md
=> [BUGFIX] Do not process frontend output for frontend:request

.gitattributes
=> [TASK] Enforce checkout with linux lf consistent over all platforms

.php_cs.dist, .styleci.yml, Tests/Console/Functional/Command/Install/InstallCommandControllerTest.php, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php, Tests/Console/Functional/Fixtures/Extensions/ext_broken_ext_tables/ext_emconf.php, Tests/Console/Functional/Fixtures/Extensions/ext_broken_ext_tables/ext_localconf.php, Tests/Console/Functional/Fixtures/Extensions/ext_broken_ext_tables/ext_tables.php
=> [BUGFIX] Add tests that cover latest regressions

Classes/Console/Command/AbstractConvertedCommand.php
=> [BUGFIX] Fix auto asking for not provided arguments

Classes/Console/Command/Upgrade/UpgradeListCommand.php, Classes/Console/Command/Upgrade/UpgradeRunCommand.php, Classes/Console/Install/Upgrade/UpgradeHandling.php, Classes/Console/Install/Upgrade/UpgradeWizardList.php, Classes/Console/Install/Upgrade/UpgradeWizardListRenderer.php, Documentation/CommandReference/UpgradeRun.rst, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php
=> [FEATURE] Allow force execution of row updaters

Classes/Console/Command/Database/DatabaseExportCommand.php
See https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-31.html#mysqld-5-7-31-security
And https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html
=> Export database without "PROCESS" privilege on MySQL 5.7.31+

Classes/Console/Install/Upgrade/UpgradeWizardList.php
=> [BUGFIX] Skip update check for wizard marked as done

Classes/Console/Command/Database/DatabaseUpdateSchemaCommand.php, Documentation/CommandReference/DatabaseUpdateschema.rst, Tests/Console/Functional/Command/DatabaseCommandControllerTest.php
=> [TASK] Improve description and error output for database:updateschema

Resources/Private/ExtensionArtifacts/composer.json, composer.json
Adapt composer.json files to new dependencies that
came up meanwhile
=> Clean up extension packaging

.github/workflows/Analyze.yml, .github/workflows/Deploy.yml, .github/workflows/Test.yml
See also https://github.com/shivammathur/setup-php#cache-composer-dependencies
=> [TASK] Enable caching for GH Actions

.github/workflows/Analyze.yml, .github/workflows/Deploy.yml, .github/workflows/Test.yml, .github/workflows/Update.yml, Resources/Private/ExtensionArtifacts/composer.json, appveyor.yml, composer.json
Although unreleased, the release is near and this change
should allow installing this package with latest
TYPO3 dev branch.
=> Allow installation with latest versions of TYPO3

Classes/Console/Error/ErrorHandler.php
=> [BUGFIX] Missing predefined constants for error_reporting

Classes/Console/Mvc/Cli/CommandDispatcher.php
Instead of relying on env vars with a version
being set, find out via reflection on runtime
how to properly construct a Process class
=> [TASK] Harden code for sub processes

Classes/Console/Install/Action/Typo3InstallAction.php, Classes/Console/Mvc/Cli/CommandDispatcher.php
=> [BUGFIX] Fix install:setup with quiet option

Classes/Console/Command/Database/DatabaseExportCommand.php, Documentation/CommandReference/CacheFlushtags.rst, Documentation/CommandReference/ConfigurationRemove.rst, Documentation/CommandReference/ConfigurationSet.rst, Documentation/CommandReference/ConfigurationShow.rst, Documentation/CommandReference/ConfigurationShowactive.rst, Documentation/CommandReference/ConfigurationShowlocal.rst, Documentation/CommandReference/DatabaseExport.rst, Documentation/CommandReference/DatabaseImport.rst, Documentation/CommandReference/DatabaseUpdateschema.rst, Documentation/CommandReference/Help.rst, Documentation/CommandReference/InstallGeneratepackagestates.rst, Documentation/CommandReference/List.rst, Documentation/CommandReference/UpgradeRun.rst, Packages/CreateReferenceCommand/src/Command/CommandReferenceRenderCommand.php
=> [FEATURE] Allow passing arbitrary arguments to mysqldump

Scripts/typo3-console.php
https://github.com/TYPO3-Console/TYPO3-Console/blob/bd81b904ca7ab552b7d134b83918552e5bffed30/Scripts/typo3-console.php#L19
ref. https://github.com/TYPO3-Console/TYPO3-Console/pull/1057
=> Remove custom PHP version check

.github/workflows/Test.yml, Classes/Console/Core/Kernel.php, Classes/Console/Mvc/Cli/Typo3CommandRegistry.php, composer.json
=> [BUGFIX] Make sure commands are instantiated with correct container

Classes/Compatibility/CompatibilityClassLoader.php
=> [BUGFIX] Remove usage of internal Composer API

Classes/Console/Error/ErrorHandler.php
Rather than throwing a TYPO3 Error Exception, now
a correct \ErrorException, which allows to hold the location of the error.
In any case, the frames need to cleaned up, to not include
the error handler which throws the exception,
but only the code that actually triggered the error.
=> [BUGFIX] Clean exception frames for error exceptions

Classes/Console/Mvc/Cli/CommandDispatcher.php
This functionionality was not implemented yet
after making everything compatible with TYPO3 12
=> [BUGFIX] Make command dispatcher work from Composer

Classes/Console/Mvc/Cli/Symfony/Descriptor/TextDescriptor.php
=> [BUG] Return type declaration must be compatible with TextDescriptor - symfony/console 6.3

Classes/Console/Service/Database/SchemaService.php
Check out https://github.com/TYPO3-Console/TYPO3-Console/issues/1146
=> Fix #1146 - Increase performance in DB compare

.github/workflows/Analyze.yml, .github/workflows/Deploy.yml, .github/workflows/Test.yml, .github/workflows/Update.yml
This makes support for PHP 8.3 official.
=> [TASK] Also run the tests with PHP 8.3

Classes/Console/Command/Backend/LockBackendForEditorsCommand.php, Documentation/CommandReference/BackendLockforeditors.rst
as adminOnly=2 allows admins AND `_cli_`
=> Add correct help text for LockBackendForEditorsCommand

.php-cs-fixer.php
This PR enables the new parallel execution feature of PHP-CS-Fixer.
=> [TASK] Enable parallel execution of PHP-CS-Fixer runs
