TYPO3-Console/TYPO3-Console

Scripts/typo3cms.php
The `vendor` directory within `typo3/cms` has been moved one level up to avoid exposure in the web root, thus incorporate this.
=> [BUGFIX] Fix typo3 autoload.php inclusion

.travis.yml, Classes/Command/DatabaseCommandController.php, Classes/Package.php, Classes/Service/Database/Exception.php, Classes/Service/Database/Schema/SchemaService.php, Classes/Service/Database/Schema/SchemaUpdateResult.php, Classes/Service/Database/Schema/SchemaUpdateType.php, Documentation/Introduction/Index.rst
This adds a "database:updateschema" command which performs database schema updates.
The types of schema updates to perform need to be specified explicitly to
avoid accidentally dropping fields/tables.
Fixes #13
=> [FEATURE] Add database schema update command

.travis.yml
Errors while building against TYPO3 master should not prevent releases.
=> [BUGFIX] Allow build failures against TYPO3 master

.travis.yml, Classes/Command/InstallCommandController.php
This is useful during deployment, e.g. to set up
the folder structure of typo3temp
=> [FEATURE] Add install:fixfolderstructure command

Classes/Core/Booting/Scripts.php
With class loader removal in [#67212](https://forge.typo3.org/issues/67212) cache_classes was removed from
the system.
This patch removes the leftover of cache_classes.
See also: https://forge.typo3.org/issues/67411
=> [TASK] Remove cache_classes from watched core cache configurations

ext_localconf.php
The install extension command does only use the install utility,
thus we need to listen to that signal to copy our script.
=> [BUGFIX] Use install utility signal to copy script

Classes/Core/ConsoleBootstrap.php, Classes/Package/UncachedPackageManager.php, Documentation/AdministratorManual/Index.rst, README.md
Remove the need to activate the extension at all.
Now only linking (or copy) to the desired directory
is needed.
=> [FEATURE] Auto activate console if possible

Classes/Composer/InstallerScripts.php, composer.json
For now the script might only be copied/linked in addition.
We have to wait for the final release of the installer
until we remove our code.
=> [FEATURE] Make script available through composer

Classes/Install/CliSetupRequestHandler.php
* Use hidden prompt for password entry (finally!!)
* Remove unnecessary usage of object manager
* Prettify error message output
=> [CLEANUP] Streamline installation process

Classes/Command/InstallCommandController.php, Classes/Install/CliSetupRequestHandler.php
If during setup the user decides to use and existing DB,
but the DB is not empty, the installation must not fail with a fatal error.
The installation process is now streamlined, that a check whether the
execution of one installation step needs to be executed is performed
before the user input is requested and after the actin was performed,
so that we can now output an error message if the action failed.
=> [BUGFIX] Fail if existing DB is selected but not empty

Classes/Command/InstallCommandController.php, Classes/Install/PackageStatesGenerator.php
The generate package states command now has a new switch
to activate system extensions that are marked as factory default
by the typo3/cms vendor. This marks all system extensions as active
that would be active after a TYPO3 setup.
=> [FEATURE] Add --activate-default-extensions switch

.travis.yml, Classes/Command/DatabaseCommandController.php, Classes/ImportExport/Database/Configuration/ConnectionConfiguration.php, Classes/ImportExport/Database/Process/MysqlCommand.php, Classes/Install/PackageStatesGenerator.php, Configuration/Console/Commands.php
This adds the feature like requested in #93 and suggested in #95
but with the conceptual change, that imports and exports are done
over stdin and stdout instead of using files.
This adds much more flexibility and is secure by default, as the output
is never stored in a file, which could be compromised.
This is also a small step to get #125 resolved.
=> [FEATURE] Add database import/export commands

Classes/Command/DatabaseCommandController.php, Classes/Database/Process/MysqlCommand.php, Classes/Mvc/Cli/CommandDispatcher.php, Classes/Mvc/Cli/InteractiveProcess.php
`database:import --interactive` now opens a mysql console
with the DB connection details taken from the TYPO3 configuration
=> [FEATURE] Add mysql interactive mode for database:import

Classes/Core/Booting/RunLevel.php, Classes/Core/Booting/Scripts.php, Classes/Core/ConsoleBootstrap.php, Classes/Package.php
This is a port for the 6.2 related branch 1.1.x.
Original commit is: https://github.com/helhum/typo3_console/commit/80146788e578addb427190d3d83f22512f062f95
Fixes #119
Fixes #57
=> Port for 1.1.x branch: [BUGFIX] Fix cache configuration in run level full

Scripts/typo3cms.php
When in non composer mode, we must not use ../ for use in
the PATH_site constant, as it has several side effects.
Fixes: #177
=> [BUGFIX] Do not use back paths for PATH_site in non composer mode

.travis.yml, Classes/Command/InstallCommandController.php
At the same time, use the same default as in previous versions
of typo3_console, which was do nothing.
Fixes #179
=> [BUGFIX] Add --site-setup-type option for non interactive install

.travis.yml, Classes/Command/BackendCommandController.php, Classes/Service/Configuration/ConfigurationService.php
The backend restriction commands are now streamlined to be more understandable.
Besides that, a documentation is added on top of the class.
Goal is to document every command controller class like that prior to 3.0 release.
This is a breaking change only for early adopters of the 3.0.x-dev branch,
as the editor lock commands were not available brforehand.
=> [TASK] Streamline and document backend restrictions

Classes/Command/DatabaseCommandController.php, Classes/Command/DocumentationCommandController.php
Instead of redirecting the stderr output of the processes
to stdout, direct it to stderr as well.
Also use console output write instead of echo in the two 
remaining places.
Fixes #194
=> [BUGFIX] Output process error output to stderr

.travis.yml, Classes/Command/DatabaseCommandController.php, Classes/Database/Schema/SchemaUpdateResult.php, Classes/Database/Schema/SchemaUpdateResultRenderer.php, Classes/Service/Database/SchemaService.php, Documentation/CommandReference/Index.rst
=> [FEATURE] Add verbose output to schema update

Classes/Command/ExtensionCommandController.php, Classes/Command/InstallCommandController.php, Classes/Mvc/Controller/CommandController.php
Make base controller class abstract
=> [CLEANUP] Doc comments and PSR-2

Classes/Composer/InstallerScripts.php, ext_localconf.php
Instead of early exiting in the slot, we just do not register
the slot in composer mode
=> [TASK] Do not register slot to copy binary in composer mode

Classes/Composer/InstallerScripts.php, composer.json
As composer now can take care to copy (or link) the binaries,
we can add an option to not additionally copy the binary
to the root directory.
This option is "install-binary" in the plugin config
and is on by default so that third party libraries can adopt the new location.
=> [FEATURE] Make it possible to disable binary copy to root

composer.json
The console in fact does not depend on the complete
typo3/cms package, but only on a few framework packages.
Point that out by adding them to the require section.
=> [TASK] Add requires for typo3/cms framework packages

Classes/Core/Booting/RunLevel.php, Classes/Core/Booting/Scripts.php, Classes/Core/Cache/FakeDatabaseBackend.php, Configuration/Console/Commands.php
At the same time it is important for the install:databasedata
command to create the database tables for the caching backend.
=> [BUGFIX] Use fake db cache backend to avoid caching

Classes/Core/Booting/Scripts.php
TIL that E_STRICT is non functional as of PHP 7
(https://wiki.php.net/rfc/reclassify_e_strict)
Since we ignore E_NOTICE, we can safely ignore E_STRICT
as well, which will cause less confusion for PHP < 7 users.
=> [BUGFIX] Remove E_STRICT as exception trigger

Scripts/typo3cms, Scripts/typo3cms.php
=> [BUGFIX] Fix obsolete trailing slash in PATH_site

.travis.yml, Classes/Command/HelpCommandController.php, Documentation/Settings.yml, Resources/Private/AutocompleteTemplates/cached.bash.tpl, Resources/Private/AutocompleteTemplates/cached.zsh.tpl, Resources/Private/ExtensionArtifacts/ext_emconf.php, ext_emconf.php
Add help:autocomplete command to generate a shell autocomplete script.
=> [FEATURE] Add shell autocomplete generation command

Classes/Command/HelpCommandController.php, Classes/Mvc/Cli/CommandManager.php, Resources/Private/AutocompleteTemplates/cached.bash.tpl, Resources/Private/AutocompleteTemplates/cached.zsh.tpl
* Make "help:help" just "help
* Make commands all lower case
* Complete commands for help command
* Alias help:autocomplete to just autocomplete
=> [TASK] Streamline auto completion script

.travis.yml, Classes/Command/CacheCommandController.php
If $groups is null, then the implode causes a warning
which is converted into an exception.
=> [BUGFIX] Avoid fatal when groups not provided

Classes/Service/CacheService.php
Instead of simply removing the cache directory on force flush,
it should be flushed instead which first moves the directory to
a temporary path and then removes it. This helps avoiding race
conditions on concurrent requests.
=> [BUGFIX] Flush cache directory on force flush

composer.json
The construct with just "||" did not work in the case
the library is already built. Replace that with "if"
=> [BUGFIX] Fix library build command

Classes/Core/Booting/RunLevel.php
cache:flush command needs to be in low runlevel
to not load extension files before clearing caches.
However it is also not useful when TYPO3 is not installed yet.
Thus we just hide it until we have a nicer bootstrap,
TYPO3 does not need extension caching any more or some
other nicer solution magically appears.
Fixes #281
=> [BUGFIX] Do not show cache:flush when T3 not installed

Configuration/Console/Commands.php
The configuration commands only need configuration
to be bootstrapped, and not the database connection
to be initialized. We can thus allow the commands to works
with a minimal bootstrap.
Fixes #292
=> [BUGFIX] Make configuration commands work without DB

composer.json
The introduced upper bound in #187 was good, but it was not taken in
mind, that the lower bound was bumped too, which prevents installing
the latest TYPO3 8.3.x version and thus not usable with it atm.
See also https://review.typo3.org/#/c/49965/
Should be cherry-picked onto master too :)
=> [BUGFIX] Debump lower bound for symfony versions

composer.json
The introduced upper bound in #187 was good, but it was not taken in
mind, that the lower bound was bumped too, which prevents installing
the latest TYPO3 8.3.x version and composer wants to fall back to TYPO3
8.3.0, which is insecure.
=> [BUGFIX] Move lower bound for symfony versions to installable one (#299)

Classes/Mvc/Cli/Command.php
The command controller must match a certain pattern.
Improve the error message if the controller does not follow
this pattern.
Fixes #303
=> [TASK] Improve error message when controller is wrong

Classes/Install/CliSetupRequestHandler.php
If the database step fails for whatever reason, we must not
try to insert something into the database because the tables
might not exist yet, but just let the error message bubble up
Fixes #302
=> [BUGFIX] Do not try to insert data if action failed

Classes/Command/InstallCommandController.php, Classes/Install/CliSetupRequestHandler.php
When asking the user for a boolean value, we now use the
the Symfony confirmation dialogue, which is easier to use.
=> [BUGFIX] Use confirmation dialogue for bool arguments

Classes/Install/PackageStatesGenerator.php
With TYPO3 master the method getAvailablePackages only returns
the active packages, unless we call scanAvailablePackages before.
We now always scan for new packages, just in case the extension list
was updated.
Fixes #297
=> [BUGFIX] Scan for packages before trying to activate them

.gitattributes, Classes/Composer/InstallerScripts.php, composer.json
Currently extension can bring their own commands, but with
TYPO3 Console not being an extension any more, these cannot
depend on it. Also other tools like Surf look for the console
in the extension directory.
Until things are sorted out, we add the possibility to add
an extension dummy in the extension directory to make dependent
extensions and external tools happy.
This option will be on by default but deprecated in master and not
deprecated in 3.x
Fixes #298
=> [BUGFIX] Install extension dummy by default

Classes/Database/Schema/SchemaUpdateResultRenderer.php, Classes/Database/Schema/SchemaUpdateType.php, Classes/Service/Database/SchemaService.php
The prefixing of fields and tables is a basically destructive schema
update, thus it is not really expected when "*.change" updates are
requested.
Fix this by splitting update suggestions into safe and destructive
statements and introducing the "field.prefix" and "table.prefix"
schema update types.
This is mildly breaking if you expect field/table prefixing upon
"*.change" but it actually ensures that your data is left untouched
unless requested otherwise.
Fixes #301
=> [BUGFIX] Do not prefix fields/tables on "*.change" DB schema update

Classes/Service/Database/SchemaService.php
Table prefixing on DB schema update are stored in the "change_table"
section.
=> [BUGFIX] Use correct statement type for table prefixing

.travis.yml, Classes/Command/ExtensionCommandController.php, Documentation/CommandReference/Index.rst
* Extend the command to be able to list active, inactive or all
* Add documentation
* Add tests
=> [TASK] Finalize extension:list command

.travis.yml, Resources/Private/ExtensionArtifacts/ext_emconf.php, composer.json
Allow installation with EM and TYPO3 8.3.x, disallow installation
with composer and > 8.3.x
Since TYPO3 does not follow semantic versioning, we must ensure that
we do not declare compatibility with a TYPO3 version, that is not released yet.
Although we cannot fix dependencies of the past, this will not affect users,
once we release a version officially compatible with TYPO3 8.4.x
=> [BUGFIX] Fix TYPO3 dependency in composer.json and ext_emconf.php

Classes/Composer/InstallerScripts.php
Ensure the base path of the dummy extension resources exists, not the files as directories.
Fixes #325
=> [BUGFIX] Fix extension dummy installation

Classes/Command/CacheCommandController.php, Classes/Service/CacheService.php, Tests/Unit/Service/CacheServiceTest.php
Because of the removal of the realurl cache table clearing workaround,
we must now take care to call the data handler API, so that realurl
hooks subscribers that clear the caches are called.
All other cache hook subscribers are thus called as well.
Nevertheless we consider this legacy API and mark the according methods
as deprecated and internal at the same time.
Nothing will be exposed to userland.
Fixes #286
=> [BUGFIX] Call data handler API when flushing caches

Classes/Core/Booting/Scripts.php, Classes/Core/ConsoleBootstrap.php, Classes/Install/CliSetupRequestHandler.php, Resources/Private/ExtensionArtifacts/src/Hook/ExtensionInstallation.php
Instead of creating the (unfortunately still required) cli user
during installation, we now create it during runtime,
if it does not exist.
This has the benefit, that we have this code in one place
and have it simplified.
This comes with a little downside, that if a disabled user already
exists, that it cannot be created any more. We accept this as the
likeliness that this happens is rather low.
This change is only slightly breaking because we at the same
time removed the MCONF name global.
=> [!!!][FEATURE] Auto-create _cli_lowlevel user

Classes/Command/DatabaseCommandController.php, Classes/Service/Database/Schema/SchemaService.php, Classes/Service/Database/Schema/SchemaUpdateType.php
The prefixing of fields and tables is a basically destructive schema
update, thus it is not really expected when "*.change" updates are
requested.
Fix this by splitting update suggestions into safe and destructive
statements and introducing the "field.prefix" and "table.prefix"
schema update types.
This is mildly breaking if you expect field/table prefixing upon
"*.change" but it actually ensures that your data is left untouched
unless requested otherwise.
Fixes #301
=> Do not prefix fields/tables on "*.change" DB schema update

Classes/Service/Configuration/ConfigurationService.php, Tests/Unit/Service/Configuration/ConfigurationServiceTest.php
Other than the TYPO3 install tool, the configuration:set command
could only deal with string values, even if the actual value to be set
was a boolean or integer.
Fix this by analyzing the current value if it exists.
Fixes #285
=> [BUGFIX] Set correct data type for configuration:set

.travis.yml, Classes/Command/ConfigurationCommandController.php, Classes/Service/Configuration/ConfigurationService.php, Classes/Service/Configuration/TypesAreNotConvertibleException.php
configuration:set did not change a configuration value
if it has been modified compared to the local configuration value.
However sometimes it is important to nevertheless write the
value to LocalConfiguration.php
Therefore we remove this restriction and only issue a warning
in this case.
=> [BUGFIX] Allow setting configuration even if not active

Classes/Command/DatabaseCommandController.php
The command database:updateschema is supposed to give
a meaningful and nice error message to users if
they used wrong change types.
For that we need to catch the correct exception and output
the error message accordingly.
=> [BUGFIX] Catch correct exception in :updateschema

Classes/Service/Database/SchemaService.php
TYPO3 considers table_clear statements to be part of
add/create/change workflow and therefore considered safe.
We must move it there so that the statements are executed
=> [BUGFIX] Use correct group for table_clear statements

Classes/Command/DatabaseCommandController.php, Classes/Database/Schema/SchemaUpdateResultRenderer.php, Classes/Database/Schema/SchemaUpdateType.php, Classes/Service/Database/SchemaService.php, Documentation/CommandReference/Index.rst, Tests/Unit/Database/Schema/SchemaUpdateTypeTest.php
Refactor the schema types to be also responsible for the
mapping to the statement types.
This has the little downside that this class now has a
dependency to internal array structure of TYPO3 schema updates,
however it is natural from a users perspective to have the
new types in this enum as well.
We now also added tests for this class and fixed some
issues found due to these tests.
Also add new documentation to explain the new possibilities.
=> [!!!][FEATURE] Add "safe" and "destructive" to database:updateschema

Classes/Command/DatabaseCommandController.php, Documentation/CommandReference/Index.rst
By default the database:updateschema command should
execute all safe actions
=> [FEATURE] Make update types optional

Classes/Command/DatabaseCommandController.php, Classes/Core/Booting/Scripts.php, Classes/Database/Schema/LegacySchemaUpdate.php, Classes/Database/Schema/SchemaUpdate.php, Classes/Database/Schema/SchemaUpdateInterface.php, Classes/Database/Schema/SchemaUpdateType.php, Classes/Service/Database/SchemaService.php, Tests/Unit/Database/Schema/SchemaUpdateTypeTest.php
Extract TYPO3 version specific code into one class with interface
to be able to register different implementations during runtime.
The database:updateschema command is now fully TYPO3 8.x compatible
Further optimize the output of the command
=> [FEATURE] Implement TYPO3 8 specific schema update

.travis.yml, Classes/Database/Schema/SchemaUpdate.php
Unlike the old API, the migrate method always needs the complete
create table statements to work correctly.
This is why we provide that and ignore the pre-selected statements.
=> [BUGFIX] Use new db schema migration API correctly

Classes/Command/CacheCommandController.php, Classes/Command/CleanupCommandController.php, Classes/Command/ConfigurationCommandController.php, Classes/Command/DatabaseCommandController.php, Classes/Command/HelpCommandController.php, Classes/Command/InstallCommandController.php, Classes/Command/SchedulerCommandController.php, Documentation/CommandReference/Index.rst, Documentation/Introduction/Index.rst, README.md, Resources/Private/CommandReference/Templates/CommandReferenceTemplate.txt
The launcher path strongly depends on the installation type and in
case of Composer also on the configuration, thus use a general path
throughout the code and docs.
=> [TASK] Use general launcher path

Classes/Install/CliSetupRequestHandler.php
The hidden input for a password broke during refactoring.
Fix the check again.
=> [BUGFIX] Hide password when typing

Classes/Core/ConsoleBootstrap.php
Check required PHP options and mute error of ini_set but echo message to console if unable to set the values.
Fixes #375
=> Check required PHP options and mute error of ini_set

.travis.yml, Classes/Command/ExtensionCommandController.php, Classes/Command/InstallCommandController.php, Classes/Extension/ExtensionSetup.php, Classes/Install/FolderStructure/ExtensionFactory.php, Classes/Property/TypeConverter/ArrayConverter.php, Tests/Functional/Fixtures/ext_test/ext_emconf.php, Tests/Functional/Fixtures/ext_test/ext_tables.sql
When calling the extension:setupactive command, the console
called TYPO3 API that is usually used when activating extensions.
However this API is called also for extensions, that are already active.
This leads to the situation, that the database schema is changed to what
the individual extension requires. If however another extension is active, that
is based on the currently activated extension, the correct schema is reverted
to state without the depending extension. Although this is fixed again, when the depending extension is processed, these operations impose a lot of overhead.
Even worse, these operations can be destructive, when the schema
changes are destructive. This is e.g. the case when a VARCHAR field is
made smaller, but already contains data exceeding the new smaller field …
=> [BUGFIX] Avoid wrong and unnecessary database schema changes

.travis.yml, Classes/Command/DatabaseCommandController.php, Classes/Command/ExtensionCommandController.php, Classes/Extension/ExtensionSetup.php, Tests/Functional/Fixtures/ext_test/ext_emconf.php, Tests/Functional/Fixtures/ext_test/ext_localconf.php, Tests/Functional/Fixtures/ext_test/ext_tables.sql
When switching to our own API for activating extensions,
it was missed that during activation is is necessary to flush
caches before performing setup operations.
Besides that, the signal sent when activating an extension
also was omitted.
So we now manually reload and flush caches and emit the signal
when required.
Fixes #385
=> [BUGFIX] Reload caches upon extension activation

Classes/Command/DatabaseCommandController.php, Classes/Service/Database/Schema/SchemaService.php, Classes/Service/Database/Schema/SchemaUpdateType.php, composer.json, ext_emconf.php
This operation is implemented in TYPO3 versions lower 8.4
and was meant to trigger a TRUNCATE TABLE in the following
situations:
1. A cache table needs to be cleared
2. An auto_increment field is added, but not the key
However the code was never executed, as these operations are not part
of the install tool database compare action.
Unfortunately typo3_console revived this previously dead code and reveals
a fatal error.
When the auto_increment field exists, but needs a change
(e.g. from INT(11) to INT(10)), then a truncate of these tables is forced.
Since these can be ANY table, it might destroy your data.
Therefore we remove this operation again from typo3_console and let
the code behind it rot in peace.
Fixes: #391
=> [BUGFIX] Remove table.clear update type

Classes/Command/DatabaseCommandController.php
The interactive database command does not show column names.
This is because `--skip-column-names` is appended to the `mysql`
command, and it cannot be overridden.
However, the parameter is not necessary, so it can easily be dropped.
=> [BUGFIX] Remove unnecessary parameter for the "mysql" command

.travis.yml, Classes/Core/Booting/Scripts.php
CLI user handling recently changed in TYPO3, so we adapt to that.
Besides that, we now detect the half baked testing framework as well
and set the paths to the build directory accordingly
=> Ensure TYPO3 master compatibility

Classes/Command/DatabaseCommandController.php
If you pass select statements to the database:import were
previously skipped. To avoid potential breakage of scripts
relying on that, we restore this functionality again,
but disable it for interactive mode.
Related: #390
=> Restore `--skip-column-names` for non interactive commands

.travis.yml, Classes/Command/ExtensionCommandController.php, Classes/Command/InstallCommandController.php, Classes/Composer/InstallerScripts.php, Classes/Core/ConsoleBootstrap.php, Classes/Install/PackageStatesGenerator.php, Configuration/Console/Commands.php, Documentation/CommandReference/Index.rst, Scripts/typo3cms.php, composer.json
Although it is pretty easy and convenient to add install:generatepackagestates
as command to be run after composer dumped its autoload information,
this isn't yet adopted widely. To change that, we use our plugin
to do so, so that the PackageStates.php file is now always written
on composer invocation.
Hopefully people using composer will eventually stop fiddling
with the extension:activate commands as of the next version of TYPO3 Console
=> [FEATURE] Always generate PackageStates.php file

.travis.yml, Classes/Core/Booting/Scripts.php
If dbal is an active extension in the current environment the database
initialization has to load dbal configuration before initializing any
database connection object. This patch ensures loading the correct
information from ext_localconf.php (setting Xclass for
DatabaseConnection).
Fixes: #403
=> [BUGFIX] Load dbal information if active

Classes/Database/Process/MysqlCommand.php
The default timeout of Symfony processes is 60 seconds which may
be too small for large database exports/imports.
=> [TASK] Raise mysql command timeout to 5 minutes

.gitattributes, .gitignore, Classes/Composer/InstallerScript/GeneratePackageStates.php, Classes/Composer/InstallerScript/InstallDummyExtension.php, Classes/Composer/InstallerScript/PopulateCommandConfiguration.php, Classes/Composer/InstallerScriptInterface.php, Classes/Composer/InstallerScripts.php, Classes/Core/Booting/Sequence.php, Classes/Core/ConsoleBootstrap.php, Classes/Mvc/Cli/RequestHandler.php, composer.json
This changes the bootstrap to load the commands
and the command manager before the RequestHandler
is initialized.
This results in a clearer Bootstrap and enables
commands being executed during composer build time.
Now every composer package (which includes TYPO3 extensions)
is scanned for console command configuration file.
All files are collected and stored in one file during build time.
During runtime this one file is evaluated instead of looping over
all active TYPO3 extensions.
Although this file has a limited format (e.g. command controller
class names must match a certain pattern), we use that
until TYPO3 Console can run native Symfony commands.
Fixes #265
=> [FEATURE] Let composer packages provide commands

Classes/Command/CacheCommandController.php, Classes/Core/ConsoleBootstrap.php, Classes/Install/CliSetupRequestHandler.php, Classes/Mvc/Cli/CommandDispatcher.php, Classes/Mvc/Cli/FailedSubProcessCommandException.php
Especially add factory methods for different contexts,
but also streamline API so that it can be used in
regular commands (like cache:flush command)
Also harden the sub process generation to work properly
in more environments (hello Windows)
=> [FEATURE] Improve command dispatcher API

Classes/Command/InstallCommandController.php, Classes/Composer/InstallerScript/GeneratePackageStates.php, Classes/Composer/InstallerScript/InstallDummyExtension.php, Classes/Mvc/Cli/CommandDispatcher.php, Classes/Mvc/Cli/ConsoleOutput.php, Scripts/typo3cms.php, composer.json
We can use the newly improved sub process API
instead of manually bootstrapping TYPO3
Also disable this functionality in case prepare-web-dir
is set to false
Fixes #411
=> [TASK] Simplify package states generation

.travis.yml, Classes/Database/Configuration/ConnectionConfiguration.php, Configuration/Console/Commands.php
A common usecase is importing an SQL dump into an empty database, thus
do not require a CLI user by switching to a minimal runlevel.
Also read all DB credentials from configuration in TYPO3 v7 since no
constants are available in minimal runlevel.
=> [BUGFIX] Fix "database:import" on empty database

.travis.yml, Classes/Command/InstallCommandController.php, Classes/Composer/InstallerScript/GeneratePackageStates.php, Documentation/CommandReference/Index.rst
Reason for that is, to be able to get a new release out
before this feature is stable enough and non breaking.
=> [TASK] Hide plugin packagestates generation behind feature flag

.travis.yml, Resources/Private/ExtensionArtifacts/ext_emconf.php, composer.json
TYPO3 Console is battle tested with the current TYPO3 master,
thus we can now safely mark it compatible with the just released
TYPO3 version 8.6.0
Also adapt our build pipeline to the latest breaking changes in the
testing framework and add further builds to include the new TYPO3 version.
=> [TASK] Mark as compatible with TYPO3 8.6

Classes/Core/ConsoleBootstrap.php
When cloning the console repo to typo3conf/ext
but not building the required extension files,
classes cannot be properly loaded by TYPO3 in non
composer mode.
Output a descriptive error message in this case.
=> Add verbose error message for layer 8 issue

composer.json
In order to avoid confusion when contributing to TYPO3 Console,
we now add typo3/cms as dev dependency, which makes it now
possible to use composer install within the console dir
to get a working contribution setup.
=> Simplify contribution workflow

Classes/Mvc/Cli/CommandDispatcher.php
The CLI RequestBuilder maps boolean arguments to a bool, but
does not consider an empty string '' to be a boolean false.
Because such arguments are already converted to boolean in the main
process, we must therefore convert this boolean value to a
string that is then correctly understood by the RequestBuilder as boolean
value.
=> [BUGFIX] Correctly pass boolean arguments to the sub process

Classes/Mvc/Cli/CommandDispatcher.php
The code path that is checked for is obsolete and does not work
anyway, neither on Windows nor nix. Therefore we remove the check
for it completely, as it triggers a failure on Windows with PHP 7.1
=> [BUGFIX] Remove buggy code path in CommandDispatcher

Configuration/Console/Commands.php
This pull request lowers the run level of database:updateschema to LEVEL_MINIMAL so it can be run without any assumptions of the existing database schema. This is useful if the database is empty.
Fixes #429
=> Run database:updateschema with RunLevel::LEVEL_MINIMAL

Classes/Command/ExtensionCommandController.php, Classes/Core/Booting/Scripts.php, Classes/Mvc/Cli/CommandManager.php, Configuration/Console/Commands.php
The cleanest way to remove TYPO3 core command controllers
is to remove them form the registry and add them to our own registry.
The we can also remove hard forcing class aliases.
=> Cleanly remove anyway overridden command controllers

Configuration/Console/Commands.php, Resources/Private/ExtensionArtifacts/ext_emconf.php, Tests/Functional/Fixtures/ext_test/ext_emconf.php
Command definition of extension:removeinactive is wrong
and effectively uses full RunLevel. This is fine
but we can then just skip the extra definition
=> 	Cleanup command definition and CGL 

appveyor.yml
It seems that in some cases the env vars are not correctly
populated to the scripts, so we explicitly set them
before executing them.
=> Stabilize Appveyor builds

Classes/Command/InstallCommandController.php, Documentation/CommandReference/Index.rst
This is essential when using `install:generatepackagestates`.
=> [TASK] Mention command to require TYPO3 core extensions

.travis.yml, Classes/Command/InstallCommandController.php, Classes/Install/CliSetupRequestHandler.php, Classes/Install/InstallStepActionExecutor.php, Classes/Mvc/Cli/CommandDispatcher.php, composer.json
Due to some changes in the install process it has become
apparent, that we need to execute the silent configuration
upgrade more often, likely directly after an action was executed.
For that we move this into the child process.
This makes the install work again, but with an error message, that
hints to to the second required fix, which is providing the database
driver.
For now we hard code it to mysqli and make it available as option
in later releases.
Fixes: #448
Closes: #449
=> [BUGFIX] Make compatible with TYPO3 8LTS

Classes/Extension/ExtensionSetup.php
When using extension:setupactive there are several steps
performed for each extension. One step is writing the
default extension configuration to LocalConfiguration.php
This is done regardless there is a configuration present already.
To avoid having the need to have write access to LocalConfiguration.php
in production, this step is now skipped when extConf for the
extension is already present for extensions that are set up
using extension:setupactive
=> [BUGFIX] Do not write extConf if present already

.travis.yml, Classes/Extension/ExtensionSetup.php, Classes/Install/CliSetupRequestHandler.php
We must not only check if the configuration is present, but
also need to check whether there is a ext_conf_template.txt
file at all.
Besides that, we must ensure that after installation all extensions
have been set up properly.
Add travis tests to verify both.
=> [BUGFIX] Do write default extConf if no extConf is present

Classes/Command/InstallCommandController.php, Documentation/CommandReference/Index.rst
Although TYPO3 is not built for being set up with a LocalConfiguration.php
to be present, it might be useful in certain (first) deployment scenarios.
Therefore we allow the installation, although it might fail with invalid
LocalConfiguration.php files
=> [BUGFIX] Enable setup with existing LocalConfiguration.php

Classes/Command/ExtensionCommandController.php, Classes/Extension/ExtensionSetup.php
The event subscribers' code must be idempotent, therefore
it save safe to emit this event every time setup is called
Fixes #444
=> [BUGFIX] Always emit extension activation signal

Classes/Install/InstallStepActionExecutor.php, Classes/Install/Upgrade/SilentConfigurationUpgrade.php, Tests/Unit/Install/InstallStepExecutorTest.php
This makes it possible to re-use it in different contexts
=> [TASK] Extract silent configuration upgrade into class

Classes/Composer/InstallerScript/InstallDummyExtension.php
This adds the composer command for changing the composer.json directly to the warning message 
this should make it easier for developer to update.
=> Add composer command for config change

.travis.yml, Classes/Command/InstallCommandController.php, Classes/Command/UpgradeCommandController.php, Classes/Composer/InstallerScript/GeneratePackageStates.php, Classes/Install/InstallStepActionExecutor.php, Classes/Install/Upgrade/UpgradeHandling.php, Classes/Install/Upgrade/UpgradeWizardExecutor.php, Classes/Install/Upgrade/UpgradeWizardFactory.php, Classes/Install/Upgrade/UpgradeWizardList.php, Classes/Install/Upgrade/UpgradeWizardListRenderer.php, Classes/Install/Upgrade/UpgradeWizardResult.php, Classes/Install/Upgrade/UpgradeWizardResultRenderer.php, Classes/Mvc/Cli/CommandDispatcher.php, Classes/Mvc/Cli/FailedSubProcessCommandException.php, Configuration/Console/Commands.php, Documentation/CommandReference/Index.rst, Tests/Unit/Install/Upgrade/Fixture/DummyUpgradeWizard.php, Tests/Unit/Install/Upgrade/UpgradeWizardExecutorTest.php, Tests/Unit/Install/Upgrade/UpgradeWizardFactoryTest.php, appveyor.yml
Add new upgrade:* commands to list necessary upgrade steps,
run through all the steps, or execute single steps out of the list.
To achieve this, a bunch of classes are added with a clean,
stable and straightforward API.
The commands handle the upgrade steps, but (of course)
do NOT perform the code update itself. This still needs
to be done manually (e.g. via Composer) beforehand.
So basically these commands are a replacement for the (manual)
click-through in the TYPO3 Install Tool AFTER code update.
=> [FEATURE] Upgrade Automation

Classes/Composer/InstallerScript/InstallDummyExtension.php
Composer does not cast the string "false" to actual false
in the extra section. Therefore we must use a "0" here
to make the composer config command write a config
that actually works.
=> [BUGFIX] Fix Composer commandline for extension dummy

Scripts/typo3cms.php
Recent refactoring broke the possibility to link
the binary to any place. Add this case to the script again.
=> [BUGFIX] Allow symlinked binary in non composer mode

Scripts/typo3cms.php
In TYPO3 master cli_dispatch.phpsh has been removed.
Check for the new script and use this as entry script
=> [BUGFIX] Check for correct entry script

Classes/Mvc/Cli/CommandDispatcher.php
This is a mitigation for #463
Use --arg=value syntax for values that contain a =
and --arg '' syntax for empty values, so that at least
sub processes work correctly
We cannot fix the toplevel entry point command though as this
needs a fix in TYPO3 (or correctly supplied syntax by the user)
=> [BUGFIX] Make empty argument values work again

.travis.yml, Classes/Command/BackendCommandController.php, Classes/Command/CacheCommandController.php, Classes/Command/ExtensionCommandController.php, Classes/Install/CliSetupRequestHandler.php, Classes/Mvc/Cli/CommandDispatcher.php, Classes/Service/CacheService.php, Tests/Functional/Command/AbstractCommandTest.php, Tests/Functional/Command/BackendCommandControllerTest.php, Tests/Functional/Command/CacheCommandControllerTest.php, Tests/Functional/Command/CleanupCommandControllerTest.php, Tests/Functional/Command/ConfigurationCommandControllerTest.php, Tests/Functional/Command/DatabaseCommandControllerTest.php, Tests/Functional/Command/DocumentationCommandControllerTest.php, Tests/Functional/Command/ExtensionCommandControllerTest.php, Tests/Functional/Command/FrontendCommandControllerTest.php, Tests/Functional/Command/HelpCommandControllerTest.php, Tests/Functional/Command/Install/InstallCommandControllerTest.php, appveyor.yml, composer.json, phpunit.xml.dist
Use command dispatcher now to execute the commands
and plain PHPUnit to compare the result with the expected result.
This is especially great for Appveyor, as we now have all tests
executed on this platform as well.
Besides that the structure for functional tests is much clearer
and more streamlined.
This change revealed some minor inconsistencies in some commands,
which are fixed as well.
=> [TASK] Move functional tests to PHPUnit

Classes/Core/ConsoleBootstrap.php
Changed so requestId is only 13 characters long.
If requestId is longer than 13 characters, inserts into sys_log will fail.
=> requestId must not be longer than 13 characters

Classes/Error/ExceptionHandler.php, Classes/Mvc/Cli/FailedSubProcessCommandException.php, Classes/Mvc/Cli/SubProcessException.php, Tests/Functional/Command/CacheCommandControllerTest.php, Tests/Functional/Command/UpgradeCommandControllerTest.php
Render failed sub process exceptions in a structured way
which includes output and error output.
Also render exceptions that occurred in the sub process
like previous exceptions including its trace in a readable way.
=> [BUGFIX] Improve exception rendering for sub processes

Classes/Core/Booting/Scripts.php, Classes/Core/ConsoleBootstrap.php
The bootstrap currently triggers some notices and TYPO3
deprecation log entries (depending on TYPO3 version),
which are now avoided.
=> [BUGFIX] Avoid deprecation log entries and notices

Classes/Install/Upgrade/UpgradeHandling.php
The upgrade:wizard command called for initial upgrade
was wrong, which resulted in it not being executed.
Since we now also check for wrong commands, it is crutial
to use the correct command name here not not make the upgrade fail.
=> [BUGFIX] Use correct command identifier in sub process

Classes/Install/Upgrade/UpgradeHandling.php, Classes/Service/Configuration/ConfigurationService.php
When performing an upgrade with multiple steps
(first to TYPO3 7.6 then 8.7), it is necessary to
check if the upgrade was done for a specific TYPO3 branch
not only if performed at all.
=> [BUGFIX] Ensure initial upgrade is done

.travis.yml, Classes/Command/InstallCommandController.php
This command tries up all TYPO3 extensions, but quits gracefully
if this is not possible.
This can be used in composer.json scripts to ensure that extensions
are always set up correctly after a composer run on development systems,
but does not fail on packaging for deployment where no
database connection is available.
Besides that, it can be used for a first deploy of a TYPO3 instance
in a new environment, but also works for subsequent deployments.
=> [FEATURE] Add install:extensionsetupifpossible command

Classes/Composer/InstallerScript/CopyTypo3Directory.php, Classes/Composer/InstallerScripts.php, appveyor.yml
We assume that tests on Appveyor fail because of strange
side effects with symlinks on Windows.
We now copy the TYPO3 directory instead of symlinking it
to be sure this is not the reason.
=> [TASK] Try again to stabilize Appveyor tests

Classes/Core/Booting/Scripts.php, Classes/Core/ConsoleBootstrap.php, Classes/Service/CacheService.php
On current TYPO3 master TYPO3_DB is not available any more,
neither the DataBaseConnection class is.
=> [BUGFIX] Do not call unavailable bootstrap method

.travis.yml, Classes/Command/UpgradeCommandController.php, Classes/Extension/ExtensionConstraintCheck.php, Classes/Install/Upgrade/SilentConfigurationUpgrade.php, Classes/Install/Upgrade/UpgradeHandling.php, Configuration/Console/Commands.php, Tests/Unit/Extension/ExtensionConstraintCheckTest.php
Before preforming any upgrade command, we now check whether
extensions are found that are marked as incompatible, as well
as individually checking if the basic extension bootstrap
would work.
Any incompatible extension found will be deactivated during this process.
This ensures that the upgrade can complete even if some incompatible
extensions are present in the system.
=> [FEATURE] Deactivate not compatible extensions on upgrade

Classes/Install/CliSetupRequestHandler.php, Classes/Install/PackageStatesGenerator.php, Classes/Mvc/Cli/CommandDispatcher.php, Tests/Functional/Command/Install/InstallCommandControllerTest.php
Also ensure that a package states file exists that reflects
the defined set of system extensions, but no third party extensions,
to avoid interference during the setup.
Besides that in the end re-create the package states file again,
flush caches and set up all extensions properly.
The end result will be a clean and desired state.
=> [BUGFIX] Only activate default exts in non composer mode

Classes/Command/CleanupCommandController.php, Classes/Core/Booting/Scripts.php, Classes/Service/Persistence/LegacyPersistenceContext.php, Classes/Service/Persistence/PersistenceContext.php, Classes/Service/Persistence/PersistenceContextInterface.php, Classes/Service/Persistence/PersistenceIntegrityService.php, Classes/Service/Persistence/TableDoesNotExistException.php, Tests/Functional/Command/AbstractCommandTest.php, Tests/Functional/Command/CleanupCommandControllerTest.php
=> [BUGFIX] Use doctrine DBAL for refindex update

Classes/Extension/ExtensionSetupResultRenderer.php
Signal slots are called for each extension, at setup extension.
To handle this, saved result must be an array
See method \Helhum\Typo3Console\Extension\ExtensionSetup::setupExtensions
=> [BUGFIX] Output all changes for commands "extension:setup*"

Classes/Install/CliSetupRequestHandler.php
Due to unsetting a wrong key, local extensions were
excluded from being activated after a setup.
Use the correct key to make it work again
=> [BUGFIX] Activate extensions after TYPO3 setup

Classes/Install/CliSetupRequestHandler.php
When extensions do not specify their dependency to TYPO3 core extensions
in a composer.json or are not installed via composer, it can happen
that generating PackageStates.php fails when doing install:setup
Since this can be considered a breaking change, we mitigate this
case now by gracefully falling back to generating a PackageStates.php
like TYPO3 does in the web installer, where only core extensions
are activated.
Fixes: #515
=> [BUGFIX] Mitigate invalid constraints error during install

Classes/Command/CacheCommandController.php, Classes/Install/CliSetupRequestHandler.php, Classes/Service/CacheService.php, Documentation/CommandReference/Index.rst, Tests/Functional/Command/CacheCommandControllerTest.php
After TYPO3 setup finished, it is necessary to flush
caches so that the extension setup catches all extensions
properly. However extensions mit ship with extra DB caches
so that the two fold cache flush fails with cf_ table
does not exist.
Therefore we need to only flush the ext_localconf file cache
only to avoid this error, but include all extension properly
for extension:setupactive
Fixes #519
=> [BUGFIX] Don't try to flush DB caches after install

Classes/Command/CacheCommandController.php, Classes/Service/CacheService.php, Documentation/CommandReference/Index.rst, Tests/Functional/Command/CacheCommandControllerTest.php
Previously flushing file caches was only done by performing
low level operations.
Now we also allow flushing file caches using the cache manager API.
Fixes #522
=> [BUGFIX] Respect cache config when flushing file caches only

Classes/Install/CliSetupRequestHandler.php
Setting up extensions can take a while, especially if they provide
data and/or file imports.
Show a message to the user that this is happening.
=> [TASK] Add hint that extensions are set up in installer

Classes/Core/ConsoleBootstrap.php
Solr generates links during indexing. For that the
CachHashCalculator might be used.
To avoid cHash to be wrongly calculated, we therefore need
to properly initialize the CachHashCalculator during boot
=> [BUGFIX] Initialize CachHashCalculator during boot

Classes/Core/Booting/RunLevel.php, Classes/Core/Booting/Scripts.php, Classes/Core/ConsoleBootstrap.php, Classes/Install/CliSetupRequestHandler.php, Configuration/Console/Commands.php, Tests/Functional/Command/AbstractCommandTest.php
We added this step to the bootstrap of
database:updateschmea command only because TYPO3 8 needs
TCA to add additional fields to the schema.
With this we however run into a chicken/egg issue, when an
extension tries to access DB (most likely a cache table)
in the process of reading ext_tables.php
Now we read TCA early on, when reading extension configuration,
which is exactly what happens in TYPO3 9 anyway,
so we can skip reading ext_tables.php for updating the DB schema.
=> [BUGFIX] Allow to update DB schema without ext_tables.php

Classes/Install/Upgrade/UpgradeHandling.php, Classes/Package/UncachedPackageManager.php
When performing an upgrade directly after deploying
the new code base, there are cases where persistent
(DB) caches need to be flushed to ensure everything
works as expected.
Fixes: #532
=> [BUGFIX] Flush caches internally before upgrade

.travis.yml, Classes/Composer/InstallerScript/CopyTypo3Directory.php, Classes/Composer/InstallerScript/GeneratePackageStates.php, Classes/Composer/InstallerScript/InstallDummyExtension.php, Classes/Composer/InstallerScript/PopulateCommandConfiguration.php, Classes/Composer/InstallerScripts.php, Classes/Composer/LegacyInstallerScripts.php, composer.json
The installer now implements a lot of things we invented here,
so we can pull in the new API from there now.
=> [FEATURE] Use new API of typo3/cms-composer-installers

Classes/Command/CacheCommandController.php, Classes/Core/Booting/RunLevel.php, Classes/Service/CacheService.php, Configuration/Console/Commands.php
It is now possible to call
typo3cms cache:flush --files-only when TYPO3 is not
set up. While this does not sound too exciting at first,
it enables usage of low level file cache flush
e.g. in composer scripts, which makes it much easier
to ensure not having some stale file caches lying around.
We now also give a nice error message in case
cache:flush is called without --files-only, but fails.
At the same time we fall back to flush files caches only
but still return an error code, to clearly communicate
that something went wrong. Otherwise one would not realize
that flushing DB caches failed for some other reason than
TYPO3 not being set up yet.
=> [FEATURE] Make cache:flush --files-only low level

Classes/Command/InstallCommandController.php, Classes/Core/Booting/RunLevel.php, Classes/Install/CliSetupRequestHandler.php
If we re-generate the package states file, we need
to ensure that no file caches with leftovers from
previously active extensions are present.
Also new extensions should trigger cache re-generation
Fixes #543
=> [BUGFIX] Ensure empty file caches for new PackageStates

Classes/Composer/InstallerScripts.php
When helhum/typo3-composer-setup is present,
we should leave setting up the web directory
to this package
=> [BUGFIX] Do not iterfere with helhum/typo3-composer-setup

Classes/Composer/InstallerScript/InstallDummyExtension.php
Since the new composer installers can distinguish between
web-dir and root-dir, we must ensure the dummy extension
is always installed in the root-dir (PATH_site)
=> [BUGFIX] If at all, the dummy extension must be in root-dir

Classes/Composer/InstallerScript/GeneratePackageStates.php, Classes/Composer/InstallerScripts.php, Classes/Composer/LegacyInstallerScripts.php, Tests/Functional/Command/Install/InstallCommandControllerTest.php
This environment variable has been introduced as feature
switch to avoid breaking changes. Therefore this feature
never really took off and people kept using composer scripts for that.
To make some things automatable but still optional,
a new package typo3-console/auto-setup will be introduced,
which (once required) generates package states during composer
build time, but also can perform a complete TYPO3 setup
and some other useful commands during development.
=> Deprecate TYPO3_CONSOLE_FEATURE_GENERATE_PACKAGE_STATES

Classes/Service/CacheService.php
When booting low level, we do not want to load the
core cache to avoid potential fatal error.
However, when we want to flush the cache, we need
to make sure we re-set the correct backend again,
so the caches are really flushed
Fixes #543
=> [BUGFIX] Flush core caches in low level flush

Classes/Core/ConsoleBootstrap.php
Don't call a method that has been removed recently.
Let's see how long we can stay compatible now :)
=> [FEATURE] Compatiblity with TYPO3 master

Classes/Command/InstallCommandController.php, Classes/Core/ConsoleBootstrap.php
It become in line with the TYPO3 7.6 bootstrap,
we initialize database constants directly after
pulling in configuration.
This fixes an edge case for not so clean extensions
that will manually initialize db connection in
ext_clocalconf.php and this relying on db constants
to be present.
Fixes #555
Fixes #540
=> [BUGFIX] Initialize database constants early

Classes/Command/CacheCommandController.php
When flushing caches, we let the sub command fail
in case there are errors
=> [BUGFIX] Throw exception on failed cache clearing

Classes/Service/CacheService.php
Although TYPO3 8 comes with doctrine, there might be
some extensions which require $GLOBALS['TYPO3_DB'],
thus we need to initialize this global as well
for TYPO3 8
=> [BUGFIX] Init DB also on TYPO3 8

Classes/Command/InstallCommandController.php, Classes/Install/PackageStatesGenerator.php, Documentation/CommandReference/Index.rst, Tests/Unit/Install/PackageStatesGeneratorTest.php
For generating PackageStates.php we now mark
local extensions as inactive when they are excluded,
even if they have been marked as protected by the
extension owner.
We now also allow framework extensions to be excluded,
but only if they are neither protected, nor provided
in the list of active framework extensions.
This makes it possible to exclude some framework extensions,
when using the --activate-default switch.
Fixes #541
=> [BUGFIX] Always exclude extensions when requested

Configuration/Console/Commands.php
Accidentally we changed cache:flush to not initialize
database connection and not re-enable caches.
Make it a full bootstrap command again
=> [BUGFIX] Cache flush command needs full bootstrap

Classes/Mvc/Cli/Command.php
Command controllers can be located in any folder per TYPO3 core rules, but TYPO3-Console throws an exception if the given command is located in a sub-folder.
See previous discussion in #303 and especially https://github.com/TYPO3-Console/TYPO3-Console/issues/303#issuecomment-327009095
The changes applied in this PR are copied from the core to accomplish the exact same behaviour.
Fixes #557
=> Allow the same pattern for command controller namespaces as the core

.travis.yml, Classes/Command/InstallCommandController.php, Classes/Install/CliSetupRequestHandler.php, Documentation/CommandReference/Index.rst, Tests/Functional/Command/Install/InstallCommandControllerTest.php
Allow to skip extension setup. This allows to make sure
installation succeeds.
While using this switch avoids issues with extensions,
it will leave the installation in a weird state,
with all third party extensions not active and
some core extensions that might not be needed in the
project being active.
=> [FEATURE] Add --skip-extension-setup to install:setup

Classes/Composer/InstallerScript/PopulateCommandConfiguration.php, Classes/Mvc/Cli/CommandCollection.php, composer.json
We now also scan composer packages for Symfony
command configurations, in both our config files
as well as in TYPO3's config files.
=> [FEATURE] Register Symfony commands from composer packages

Classes/Mvc/Cli/CommandCollection.php, Classes/Mvc/Cli/Symfony/Command/CommandControllerCommand.php, Classes/Mvc/Cli/Symfony/Command/HelpCommand.php, Configuration/Console/Commands.php
It is now possible to override/ replace/ remove
commands from other packages (or even the core
or TYPO3 Console themselves).
A package can define a "replace" section in the
configuration with an array of command identifiers.
Commands having these identifiers will be skipped
in any case, whether they really have a replacement
or not.
=> [FEATURE] Allow replacing commands from other packages

Classes/Command/CacheCommandController.php, Classes/Command/DatabaseCommandController.php, Classes/Command/DocumentationCommandController.php, Classes/Command/SchedulerCommandController.php, Classes/Mvc/Cli/CommandCollection.php, Classes/Mvc/Cli/Symfony/Command/CommandControllerCommand.php, Classes/Mvc/Cli/Symfony/Descriptor/TextDescriptor.php, Classes/Mvc/Controller/CommandController.php, Configuration/Console/Commands.php, Documentation/CommandReference/Index.rst
Command controller commands used to also work
with their full identifier. Mimik this behavior
again by setting the according alias.
Nevertheless we deprecate the usage of such
command names.
=> [BUGFIX] Define aliases for command controller commands

Classes/Command/CacheCommandController.php, Classes/Service/CacheService.php, Configuration/Console/Commands.php
The command cache:flushcomplete must not boot to
a level where a db connection is needed, otherwise
it will fail before we reach the cache service.
On the other hand, we need to re enable the core caches
also when flushing database caches, so that the will
in fact be flushed and we are not operating with the
fake database backend
=> [BUGFIX] Make low level cache flush work again

Classes/Command/HelpCommandController.php, Classes/Mvc/Cli/Command.php, Classes/Mvc/Cli/CommandArgumentDefinition.php, Classes/Mvc/Cli/Symfony/Command/CommandControllerCommand.php, Classes/Mvc/Cli/Symfony/Command/HelpCommand.php, Classes/Mvc/Cli/Symfony/Descriptor/TextDescriptor.php
Remove all of our own code and instead convert the command definition
to a Symfony input definiton and let the descriptor do its job
=> [FEATURE] Use Symfony help also for command controller commands

.travis.yml, Classes/Command/ExtensionCommandController.php, Classes/Command/InstallCommandController.php, Classes/Command/SchedulerCommandController.php, Classes/Core/Kernel.php, Classes/Mvc/Cli/Symfony/Application.php, Classes/Mvc/Cli/Symfony/Command/CommandControllerCommand.php, Classes/Mvc/Controller/CommandController.php, Configuration/Console/Commands.php, Documentation/CommandReference/Index.rst, Tests/Functional/Command/AbstractCommandTest.php, Tests/Functional/Command/ExtensionCommandControllerTest.php, Tests/Functional/Command/UpgradeCommandControllerTest.php
When TYPO3 is composer managed, these commands were
deprecated to be used. Instead a fully automated
workflow using package states generation and
extension:setupactive command should be used.
=> [!!!] Hide extension:de/activate in composer mode

.travis.yml
We currently only use "parallel" for php linting,
which is fast enough without parallel execution.
By not installing "parallel" setting up the build
machines is slightly faster.
=> Do not install "parallel" on Travis

Classes/Command/FrontendCommandController.php
When the public document root directory does only has
public assets and the entry scripts, we must use this
directory as base, not PATH_site (which only has dummy
entry scripts)
=> [BUGFIX] Make frontent:request work with public document root

Classes/Command/ExtensionCommandController.php, Configuration/Console/Commands.php
This command, because being located in ExtensionCommandController,
needs TYPO3_DB being preset because of the multiple
dependency injected objects.
So we execute this bootstrap step and at the same time
lower the run level compile to avoid other errors
by having disabled caches.
Fixes #609
Fixes #610
=> [BUGFIX] Use compile level for extension:dumpautoload

Classes/Install/Upgrade/UpgradeHandling.php, Classes/Install/Upgrade/UpgradeWizardFactory.php, Classes/Install/Upgrade/UpgradeWizardList.php, Classes/Install/Upgrade/UpgradeWizardListRenderer.php, Classes/Install/Upgrade/UpgradeWizardResultRenderer.php, Tests/Unit/Install/Upgrade/UpgradeWizardFactoryTest.php
Instead of hard coding a list of wizards that install
extensions, we now check if the wizard extends the
abstract class. By that we now track more wizards,
which were previously missing in the hard coded list.
Also fix getting the wizard object in this porcess
for non composer mode.
Last but not least, add warning messages in composer mode
to notify users that extensions have not been installed,
thus might be lacking after the upgrade.
=> Fix upgrade handling of extension install wizards

Classes/Command/CacheCommandController.php, Tests/Functional/Command/CacheCommandControllerTest.php
To flush caches, we need to know which caches exist.
In TYPO3 extensions can provide their own caches in ext_localconf.php
So we need to load these files to be able to flush all caches.
However two introduced changes in TYPO3 hinder us to do so.
1. Exceptions are thrown when extension configuration does not exist.
The new extension configuration API in TYPO3 9.0 throws exceptions
and is used in ext_localconf.php files in core extensions.
Therefore it is never possible to load these files without having
a LocalConfiguration.php present, which contains such configuration.
2. Loading TCA now requires a database connection
Since we also load TCA in the same booting step with including
ext_localconf.php files, flushing caches will always fail,
when no database connection is configured (no …
=> [BUGFIX] Gracefully exit when flushing file caches in pre-install state

Classes/Core/Booting/RunLevel.php, Classes/Core/Booting/Scripts.php, Configuration/Console/Commands.php
Since TYPO3 introduced the requirement to have a DB
connection when generating TCA caches, we cannot initialize
TCA early in the bootstrap, but must postpone it to a later stage
when we can be sure a database connection can be established.
=> [BUGFIX] Do not initialize TCA without DB connection

Classes/Service/CacheService.php
Before loading ext_tables.php of extensions, we need
to make sure TCA is loaded.
=> [BUGFIX] Initialize TCA in cache service

Classes/Command/ExtensionCommandController.php, Classes/Command/InstallCommandController.php, Classes/Install/PackageStatesGenerator.php, Classes/Mvc/Cli/CommandDispatcher.php, Classes/Mvc/Cli/ConsoleOutput.php, Classes/Mvc/Cli/Symfony/Application.php, Classes/Mvc/Cli/Symfony/Command/CommandControllerCommand.php, Documentation/CommandReference/Index.rst, Resources/Private/ExtensionArtifacts/src/Hook/ExtensionInstallation.php, Tests/Functional/Command/UpgradeCommandControllerTest.php, Tests/Unit/Install/PackageStatesGeneratorTest.php
Instead of removing them without deprecation, we deprecate them now,
so we can remove them with TYPO3 Console 6
=> [TASK] Bring back and deprecate extension:(de)activate commands

Classes/Command/BackendCommandController.php, Documentation/CommandReference/Index.rst, Tests/Functional/Command/BackendCommandControllerTest.php
I've created a suggestion on how to do the "create user", but I'm not fully happy due to duplicate code from the core.
The adjustments made are more or less copy/paste from the core from the InstallTool Important Actions.
typo3/sysext/install/Classes/Controller/Action/Tool/ImportantActions.php Line: 157-211 
typo3/sysext/install/Classes/Controller/Action/AbstractAction.php Line: 203-213
I haven't find a better way to do this, but duplicate code is really not prefered. 
If you have any suggestions I will be happy to adjust the code.
=> Allows you to create backend users from cli

Classes/Install/CliSetupRequestHandler.php, Classes/Install/InstallStepActionExecutor.php, Classes/Mvc/Cli/CommandDispatcher.php, Compatibility/TYPO3v87/Install/InstallStepActionExecutor.php
Instead of letting the installer fail, we catch exceptions
that can occur when executing an install step and output
the exception message as error message.
Fixes: #621
=> [BUGFIX] Catch install step exceptions and output error

Classes/Command/DatabaseCommandController.php, Classes/Database/Process/MysqlCommand.php
Instead of passing the password as argument, which is considered
insecure as other users can see this when listing processes,
we now create a config file on the fly in which we store the
username and password.
Fixes: #625
=> [FEATRUE] Do not pass password as argument to mysql

Classes/Command/DatabaseCommandController.php, Tests/Functional/Command/DatabaseCommandControllerTest.php
Instead we use --single-transaction, which might lead to
inconsistent results on MyIsam tables, but that still
is ok for our purpose (which is not creating backups)
Because the changes of behaviour for this command,
it is justified to mark this as breaking change,
although you may only be affected when you need
100% consistency and don't have all tables on InnoDB.
Fixes: #432
=> [!!!][FEATURE] Do not lock tables when dumping sql in database:export

Classes/Command/CleanupCommandController.php, Classes/Command/ConfigurationCommandController.php, Classes/Command/DocumentationCommandController.php, Classes/Command/ExtensionCommandController.php, Classes/Command/InstallCommandController.php, Classes/Command/SchedulerCommandController.php, Classes/Mvc/Cli/Command.php, Classes/Service/XsdGenerator.php, Compatibility/TYPO3v87/Mvc/Cli/Command.php
All classes especially command controllers now use
constructor injection for DI.
Only the base CommandController class is left with two
inject methods to not require subclasses to call the
parent constructor.
=> [TASK] Consistently use constructor injection

Classes/Command/CleanupCommandController.php, Classes/Command/DatabaseCommandController.php, Classes/Command/ExtensionCommandController.php, Classes/Command/InstallCommandController.php, Classes/Command/UpgradeCommandController.php, Classes/Mvc/Cli/ConsoleOutput.php, Classes/Mvc/Cli/Symfony/Command/CommandControllerCommand.php, Classes/Mvc/Cli/Symfony/Descriptor/TextDescriptor.php, Documentation/CommandReference/Index.rst
Instead of always re-declaring options like --verbose,
use the global option.
Now all global options are shown for every command help
=> [FEATURE] Prefer global option over declaring local ones

Classes/Mvc/Cli/CommandDispatcher.php, Classes/Mvc/Cli/Symfony/Application.php
When the env var PHP_INI_PATH is set, we instruct PHP
to load it for sub processes.
Fixes: #528
=> [FEATURE] Allow to specify php.ini path for sub processes

.travis.yml, Classes/Command/DatabaseCommandController.php, Classes/Command/FrontendCommandController.php, Classes/Core/Kernel.php, Classes/Database/Process/MysqlCommand.php, Classes/Mvc/Cli/CommandDispatcher.php, Tests/Functional/Command/AbstractCommandTest.php, composer.json, phpunit.xml.dist
Remove usages of ProcessBuilder as this class was removed
with Symfony 4.0.0
Raise minimum Symfony version to 3.3.6 as only as of then
the Process class can deal with array as command line
and this is the version currently shipped with TYPO3 ^8
Add --prefer-lowest to our builds to be sure we still run
with lowest possible package versions
=> [FEATURE] Make compatible with Symfony >= 4.0

Classes/Core/Kernel.php, Classes/Install/CliSetupRequestHandler.php, Classes/Mvc/Cli/CommandDispatcher.php, Compatibility/TYPO3v87/Core/Booting/CompatibilityScripts.php
Since composer still uses symfony/* in versions 2.7.x
and we conflict in some areas with that version,
we need to adapt our code a bit so that the triggered
code is able to run with symfony/*
=> [BUGFIX] Fix setup during composer run

Classes/Core/Kernel.php, composer.json
In order for the compatibility layer to work, the Compatiblity
folder must also be registered in the class loader.
We now change the non composer class loading to register
all psr-4 namespaces directly from the composer.json file,
which will avoid issues in the future.
With this change we also simplify the autoload section
in our composer.json
Fixes: #655
=> [BUGFIX] Correctly register class loading in non composer mode

Classes/Mvc/Controller/CommandController.php
In previous versions of typo3 console and in the pure
TYPO3 implementation the command method return value
is set as response content. This content is then later
just echo'ed out, not respecting the output object that is used
otherwise, which means formatting is never applied.
For the sake of backwards compatibility we now output the
command method result again, but properly use the output object
and at the same time deprecate this functionality, as it
isn't very helpful to implicitly output something while
it is equally simple to use the output API explicitly.
Fixes: #658
=> [BUGFIX] Output command method return value, but deprecate it

Resources/Private/ExtensionArtifacts/src/Hook/ExtensionInstallation.php
When updating the standalone extension (non-composer mode) in the
Extension Manager make sure to use the correct check for an existing
typo3cms binary.
Fixes: #657
=> [BUGFIX] Search for correct substring in existing binary on updates

Classes/Install/CliSetupRequestHandler.php, Classes/Install/InstallStepActionExecutor.php, Tests/Functional/Command/Install/InstallCommandControllerTest.php, appveyor.yml
Because TYPO3 core installer class does not implement
the method to check whether this last step was executed
and we checked if the action needs to be executed again
right after execution and by default we assumed yes,
the action was triggered twice.
Since this action deletes the first install file,
we change the default whether the action needs to
be executed to existence of this file.
Fixes: #668
=> [BUGFIX] Do not call last install step twice

Classes/Core/Kernel.php, Classes/Mvc/Cli/CommandCollection.php, composer.json
Instead of instantiating all command objects upfront
before running the application, we now use a command
provider, that is creating command objects on demand.
This should improve startup time when running individual commands,
especially if commands have heavy initializations.
This also fixes a bug when TYPO3 Symfony commands were
accessing TYPO3 state in the constructor, which was not possible,
due to early instantiation.
Fixes: #675
=> [FEATURE] Use CommandLoader API of symfony/console

.gitattributes, Classes/Command/CacheCommandController.php, Classes/Command/CleanupCommandController.php, Classes/Command/ConfigurationCommandController.php, Classes/Command/DatabaseCommandController.php, Classes/Command/HelpCommandController.php, Classes/Command/InstallCommandController.php, Classes/Command/SchedulerCommandController.php, Classes/Mvc/Cli/CommandCollection.php, Classes/Mvc/Cli/Symfony/Command/CommandControllerCommand.php, Commands/CreateReferenceCommand/.gitignore, Commands/CreateReferenceCommand/Configuration/Console/Commands.php, Commands/CreateReferenceCommand/Resources/Templates/CommandReferenceTemplate.txt, Commands/CreateReferenceCommand/composer.json, Commands/CreateReferenceCommand/src/Command/CommandReferenceRenderCommand.php, Commands/CreateReferenceCommand/src/ViewHelpers/Format/IndentViewHelper.php, Commands/CreateReferenceCommand/src/ViewHelpers/Format/UnderlineViewHelper.php, Configuration/Console/Commands.php, Documentation/CommandReference/Index.rst, composer.json
Instead of maintaining a separate repo for the command,
that renders the reference, we include it in our main repo now.
With this change, we rework the rendering to use a Symfony application
description instead of the command manager a base to generate
the reference.
Result is a more consistent reference, that matches the existing commands
better than before.
This also enables us to slowly migrate from command controllers
to native Symfony commands, but still have these in the reference.
=> [BUGFIX] Use Symfony application description to render reference

Commands/CreateReferenceCommand/src/Command/CommandReferenceRenderCommand.php, Tests/Functional/Command/UpgradeCommandControllerTest.php
Since TYPO3 master updated doctrine/dbal we need to
update that package as well when upgrading code.
Also exclude swiftmailer command from our reference.
=> Fix master build on travis

.travis.yml, Classes/Core/Kernel.php, Tests/Functional/Command/UpgradeCommandControllerTest.php, Tests/Functional/Fixtures/Extensions/ext_test/ext_tables.sql, appveyor.yml, composer.json
Mostly tests adjustments.
Remove call to Bootstrap::shutdown, which was there
for compatibility anyway and does nothing TYPO3 Console needs
=> [BUGFIX] Provide compatibility with TYPO3 master

Classes/Mvc/Cli/CommandCollection.php
With making CommandCollection a CommandLoader, the handling
for command aliases got lost.
Make the collection aware of aliases. For that to work,
we need a way to define aliases upfront in configuration,
otherwise we would need to instantiate all commands
upfront again, which would make the CommandLoader
obsolete again.
=> [BUGFIX] Implement alias handling in CommandCollection

Classes/Composer/InstallerScript/PopulateCommandConfiguration.php, Classes/Core/Booting/RunLevel.php, Classes/Core/Kernel.php, Classes/Mvc/Cli/CommandCollection.php, Classes/Mvc/Cli/CommandConfiguration.php, Commands/CreateReferenceCommand/Configuration/Console/Commands.php, Configuration/Console/Commands.php, Tests/Functional/Command/DatabaseCommandControllerTest.php, Tests/Unit/Core/Booting/RunLevelTest.php, Tests/Unit/Fixtures/Command/TestCommandController.php, Tests/Unit/Mvc/Cli/CommandConfigurationTest.php, appveyor.yml, phpunit.xml.dist
I order to be able get rid of Configuration/Console/Commands.php
in the future, we now unify command registration.
All commands can now be registered with
"command:name" => [
// Command configuration
]
This includes also commands from command controllers.
Run level, booting steps, replaces, aliases and vendor name
are now part of this configuration. All these are optional
with proper defaults in case they are missing.
Defaults are:
runLevel: full
booting steps: none
replaces: none
aliases: none
vendor name: package name (or extension key for TYPO3 extensions)
This allows to specify arbitrary aliases also for
command controller commands. Even different command names would be possible.
Old registration and command controllers registered in …
=> [FEATURE] Unify command registration

Classes/Console/Core/Kernel.php, Resources/Private/ExtensionArtifacts/autoload.php, Resources/Private/ExtensionArtifacts/ext_emconf.php, Resources/Private/ExtensionArtifacts/ext_localconf.php, Scripts/typo3-console.php
We now always add our class prefixes to the main
class loader and disable other registration for
console classes.
This helps to fix an edge case where old class loading
info has overwritten what was added before.
While doing so, all non composer class loading code
is extracted to a autoload.php file, which is only
loaded when console is not installed with composer.
With that, we can remove remaining class_exists and
one composer mode check from bootstrap.
Fixes: #667
=> [BUGFIX] Harden class loading in non composer mode

.travis.yml, Classes/Compatibility/TYPO3v87/Core/Booting/CompatibilityScripts.php, Classes/Compatibility/TYPO3v91/Core/Booting/CompatibilityScripts.php, Classes/Console/Core/Booting/Scripts.php, Classes/Console/Core/Kernel.php, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php, composer.json
To avoid deprecation messages early on, which might pollute
console output, we add different code for different
package manager creation in 8.7 and upcoming 9.2
=> Avoid deprecation messages with TYPO3 master

Classes/Console/Core/Kernel.php, Classes/Console/Mvc/Cli/CommandDispatcher.php
Include phpdbg in SAPI check and add phpdbg
arguments properly for sub processes.
=> [BUGFIX] Allow phpdbg PHP SAPI

Classes/Console/Command/ExtensionCommandController.php, Tests/Console/Functional/Fixtures/Extensions/ext_test/ext_localconf.php
Cache needs to be flushed before ext_localconf.php files
are loaded, because those can define new caches with
database backend, thus a cache:flush will try to flush those
without the tables being present.
=> [BUGFIX] Fix extension:activate when extension defines caches

.travis.yml, appveyor.yml, composer.json
To not require a clone of the testing framework to be present
on local installs, we now change the repository url back
to the remote repository and change it back to the local
clone on travis and appveyor
=> Improve fetching testing framework fork

.travis.yml, Classes/Compatibility/TYPO3v87/Install/CliMessageRenderer.php, Classes/Console/Annotation/Command/Definition/Option.php, Classes/Console/Command/InstallCommandController.php, Classes/Console/Core/Kernel.php, Classes/Console/Install/Action/CommandsAction.php, Classes/Console/Install/Action/ExtensionSetupAction.php, Classes/Console/Install/Action/InstallActionDispatcher.php, Classes/Console/Install/Action/InstallActionFactory.php, Classes/Console/Install/Action/InstallActionInterface.php, Classes/Console/Install/Action/InteractiveActionArguments.php, Classes/Console/Install/Action/PrepareInstallAction.php, Classes/Console/Install/Action/Typo3InstallAction.php, Classes/Console/Install/CliMessageRenderer.php, Classes/Console/Install/CliSetupRequestHandler.php, Classes/Console/Install/StepsConfig.php, Classes/Console/Mvc/Cli/Command.php, Classes/Console/Mvc/Cli/ConsoleOutput.php, Classes/Console/Mvc/Cli/Symfony/Output/TrackableOutput.php, Configuration/Install/InstallSteps.yaml, Documentation/CommandReference/Index.rst, Packages/CreateReferenceCommand/Resources/Templates/CommandReferenceTemplate.txt, Tests/Console/Functional/Command/Install/InstallCommandControllerTest.php, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php, composer.json, sonar-project.properties
The previous implementation came with a lot of downsides.
The main class performing the setup was incredibly complex
and hard to understand. Besides that, it required Extbase
ObjectManager, which in turn needed a TYPO3 bootstrap to
be performed. Because of the latter, we needed to perform
a TYPO3 boot when triggering this setup during a composer install.
Last but not least, all steps were hard coded in this god class,
which made it impossible to add or amend steps. Even extending
this class would have been hard.
Therefore this process is rewritten from scratch, distributed
into several classes and made extendable by simply providing
a different Yaml file, which now defines which actions are taken
during installation.
As a long hanging fruit it is now implemented, that all
setup arguments …
=> [FEATURE] Rewrite TYPO3 setup process

.gitattributes, Classes/Console/Install/StepsConfig.php, Resources/Private/Patches/patches.json, Resources/Private/Patches/phpunit-env.diff, Tests/Console/Functional/Command/Install/InstallCommandControllerTest.php, Tests/Console/Functional/Fixtures/Install/custom-install-import.yaml, Tests/Console/Functional/Fixtures/Install/custom-install.yaml, composer.json, phpunit.xml.dist
It is now possible to specify a different install step
file by providing the TYPO3_INSTALL_SETUP_STEPS environment
variable.
Example:
TYPO3_INSTALL_SETUP_STEPS=/path/to/steps.yaml typo3cms install:setup
=> [FEATURE] Allow specifying alternative install steps

Classes/Console/Mvc/Cli/CommandDispatcher.php
The first argument is obsolete for a while and is now deprecated.
No deprecation message is thrown to not conflict with weird TYPO3
error handlers.
=> [TASK] Deprecate first argument for CommandDispatcher::createFromComposerRun()

Classes/Console/Command/InstallCommandController.php, Classes/Console/Install/Action/InstallActionDispatcher.php, Classes/Console/Install/Action/InstallationFailedException.php, Classes/Console/Install/Action/PrepareInstallAction.php
Install actions currently can throw exceptions to abort,
but we now introduce an exception that makes the installation
abort, but gracefully let's the dispatcher return false
instead of letting the exception bubble up.
We use this now to add the integrity check to the preparation step
and removing this check from the command controller.
=> [FEATURE] Make it possible to abort installation process

Classes/Console/Command/DatabaseCommandController.php
It's a nice option and shouldn't break anything.
`typo3console database:export -v` or `--verbose` now makes `mysqldump` verbose too. Mysqldump outputs its information using stderr so piping the dump into a file still works.
=> add verbose option to database:export

Classes/Console/Command/DatabaseCommandController.php, Classes/Console/Database/Schema/TableMatcher.php, Documentation/CommandReference/Index.rst, Tests/Console/Functional/Command/DatabaseCommandControllerTest.php, Tests/Console/Unit/Database/Schema/SchemaUpdateTypeTest.php, Tests/Console/Unit/Database/Schema/TableMatcherTest.php
Allow specifying wildcards to database:export like:
typo3cms database:export --exclude-tables 'cf_*,cache_*'
=> [FEATURE] Support wildcards for excluding tables on export

Classes/Console/Command/DatabaseCommandController.php, Classes/Console/Database/Process/MysqlCommand.php, Documentation/CommandReference/Index.rst, Tests/Console/Functional/Command/DatabaseCommandControllerTest.php
Since TYPO3 v8 is it possible to use multiple databases in one TYPO3 installation. Every database became a connection (default: "Default"). With this new argument is it possible to export and import data from or to a defined connection.
**Example (import):** `ssh remote.server '/path/to/typo3cms database:export' | typo3cms database:import --connection="OtherDatabase"`
**Example (export):** `typo3cms database:export --connection="OtherDatabase"`
=> [FEATURE] Add argument to select database connection

.travis.yml, Classes/Console/Command/AbstractConvertedCommand.php, Classes/Console/Command/Database/DatabaseExportCommand.php, Classes/Console/Command/DatabaseCommandController.php, Classes/Console/Mvc/Cli/Symfony/Descriptor/TextDescriptor.php, Configuration/Console/Commands.php, Documentation/CommandReference/Index.rst, Packages/ConvertCommandControllerCommand/.gitignore, Packages/ConvertCommandControllerCommand/Configuration/Console/Commands.php, Packages/ConvertCommandControllerCommand/composer.json, Packages/ConvertCommandControllerCommand/src/Command/ConvertCommandControllerCommand.php, Packages/CreateReferenceCommand/src/Command/CommandReferenceRenderCommand.php, Tests/Console/Functional/Command/DatabaseCommandControllerTest.php, composer.json
This allows us to use dedicated Symfony features like
array values for options and short option names.
This change also comes with an abstract class, which should
ease conversion of other commands and still handling
backwards compatibility.
=> [FEATURE] Make database:export a native Symfony command

Classes/Console/Mvc/Cli/CommandArgumentDefinition.php
Fix #738
This commit is meant to replace commit 63d69bdc76b3cb4e5d62b285fb49ecdec744d716
=> Support command options with a single character name

Resources/Private/ExtensionArtifacts/ext_emconf.php
This has been merged into core with TYPO3 9.4 and there is no replacement concept for TYPO3 extensions.
Fixes #749
=> [BUGFIX] Drop dependency on saltedpasswords

.travis.yml, Classes/Console/Install/Upgrade/UpgradeWizardExecutor.php, Classes/Console/Install/Upgrade/UpgradeWizardList.php, composer.json
That we hotfixed the code for 9.4 release now caught us again
so that we need to hot fix it a gain due to recent changes.
Fingers crossed this is the last time.
The whole upgrade functionality needs some heavy cleanup and
restructuring later.
=> [BUGFIX] Hotfix Upgrade wizard code to be able to release

Classes/Console/Core/Booting/RunLevel.php, Classes/Console/Core/Booting/Sequence.php, Classes/Console/Core/Booting/StepFailedException.php, Classes/Console/Core/Kernel.php, Classes/Console/Mvc/Cli/Symfony/Application.php
Instead of failing before starting the console application,
we now catch booting errors and output them once the IO
is properly configured.
This means the following:
* Booting errors for all registered commands will lead to an exception just like before.
* list and help commands gracefully work but return exit code 255 and show a tiny error message
* list and help commands also throw the exception when output is verbose
This ensures that no command is executed in limbo state, except help and list,
which are not changing any state.
As "side effect" auto completion will still work, even if the current installation
is broken.
=> [FEATURE] Delay output of booting errors

Classes/Console/Command/Extension/DumpAutoloadCommand.php, Classes/Console/Command/ExtensionCommandController.php, Classes/Console/Core/Booting/RunLevel.php, Classes/Console/Core/Kernel.php, Classes/Console/Exception/CommandNotAvailableException.php, Classes/Console/Mvc/Cli/CommandCollection.php, Classes/Console/Mvc/Cli/Symfony/Application.php, Classes/Console/Mvc/Cli/Symfony/Command/CommandControllerCommand.php, Classes/Console/Mvc/Cli/Symfony/Command/ListCommand.php, Classes/Console/Mvc/Cli/Symfony/Descriptor/TextDescriptor.php, Configuration/Commands.php, Documentation/CommandReference/Index.rst, Packages/CreateReferenceCommand/src/Command/CommandReferenceRenderCommand.php, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php
First and foremost, we now always register all commands under
all circumstances. This means, that auto completion will always
work properly. The command listing will still be reduced to the commands
that are likely to work, but optionally allows showing all commands.
Also show a more helpful error message when executing a command
which cannot be run unless TYPO3 is set up instead of showing
an error message that the command does not exist (which is in fact wrong)
=> [FEATURE] Show more helpful messages in error conditions

Classes/Console/Command/InstallCommandController.php, Classes/Console/Install/CliMessageRenderer.php, Configuration/Install/InstallSteps.yaml, Documentation/CommandReference/Index.rst, Tests/Console/Functional/Command/Install/InstallCommandControllerTest.php
Since we now only support doctrine only TYPO3 versions
(8.7 and 9.5), we can safely ask for alternative drivers,
but fall back to mysqli as default if none is provided.
Fixes: #450
=> [BUGFIX] Provide option to select driver on install:setup

.travis.yml, Classes/Console/Install/Upgrade/UpgradeWizardExecutor.php, Classes/Console/Install/Upgrade/UpgradeWizardFactory.php, Tests/Console/Unit/Install/Upgrade/Fixture/ChattyUpgradeWizard.php, Tests/Console/Unit/Install/Upgrade/UpgradeWizardExecutorTest.php
Ensure upgrade wizards implementing ChattyInterface and
using the output in updateNecessary method work correctly
and output is tracked and returned correctly.
Fixes: #788
=> [BUGFIX] Fix execution of chatty upgrade wizards

Resources/Private/ExtensionArtifacts/Classes/Console/Hook/ExtensionInstallation.php
For extension manager web ui we must store the flash message
in the session, but a session is not available on cli,
so we skip creating a flash message altogether.
Fixes: #776
=> [BUGFIX] Avoid creating flash message on cli

Classes/Compatibility/TYPO3v87/Service/CacheLowLevelCleaner.php, Classes/Console/Command/Cache/CacheFlushCommand.php, Classes/Console/Command/CacheCommandController.php, Classes/Console/Mvc/Cli/Symfony/Application.php, Classes/Console/Service/CacheLowLevelCleaner.php, Classes/Console/Service/CacheService.php, Configuration/Commands.php, Documentation/CommandReference/Index.rst, Tests/Console/Functional/Command/CacheCommandControllerTest.php, Tests/Console/Unit/Service/CacheServiceTest.php
This command needs to be as resilient as possible,
therefore many dependencies from the classes have been
removed, especially the dependency to Extbase DI API,
which requires caching and lead to chicken/egg issues,
when we changed our API.
Additionally we now removed the --force flag, as in practice
this options is used all the time, so we make it default
and non optional to low level remove files and truncate db tables.
Fixes: #770
=> [BUGIFX] Simplify and harden cache:flush command

Classes/Console/Command/AbstractConvertedCommand.php, Classes/Console/Command/Cache/CacheFlushCommand.php, Classes/Console/Command/Documentation/GenerateXsdCommand.php, Classes/Console/Command/DocumentationCommandController.php, Configuration/Commands.php, Documentation/CommandReference/Index.rst, Tests/Console/Functional/Command/Documentation/GenerateXsdCommandTest.php
The old class is marked as deprecated, as it is not in
use anymore.
New options for generateXsd are available:
-xsd
-target
=> [TASK] Migrate documentation:generateXsd to native command

Classes/Console/Install/Upgrade/UpgradeWizardExecutor.php
The UpgradeWizardExecutor uses the class name of the wizard
as the registry key for marking the wizard done.
This makes the behavior consistent with TYPO3.
Resolves: #795
=> [BUGFIX] Use wizard class name to mark wizard done

Classes/Console/Install/Action/WriteWebServerConfigAction.php
When executing TYPO3 setup in composer context, we do
not have the Environment object nor PATH_site set up
because TYPO3 is not booted. Therfor we must not
rely on any of those.
=> [BUGFIX] Fix writing webserver config from composer install

Classes/Console/Command/UpgradeCommandController.php, Classes/Console/Install/Upgrade/UpgradeHandling.php
Instead of silently deactivating extensions, we now fail
if incompatible extensions are found during an upgrade:run run.
Fixes: #720
=> [BUGFIX] Fail upgrade when incompatible extensions are found

.travis.yml, Classes/Console/Install/Upgrade/UpgradeWizardExecutor.php, Classes/Console/Install/Upgrade/UpgradeWizardList.php, Resources/Private/ExtensionArtifacts/composer.json, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php, Tests/Console/Unit/Install/Upgrade/Fixture/DummyUpgradeWizard.php, Tests/Console/Unit/Install/Upgrade/Fixture/LegacyUpgradeWizard.php, Tests/Console/Unit/Install/Upgrade/Fixture/RepeatableUpgradeWizard.php, Tests/Console/Unit/Install/Upgrade/LegacyWizardExecutorTest.php, Tests/Console/Unit/Install/Upgrade/UpgradeWizardExecutorTest.php, Tests/Console/Unit/Install/Upgrade/UpgradeWizardFactoryTest.php, appveyor.yml, composer.json, phpunit.xml.dist
The `RepeatableInterface` isn't respected and repeatable wizards are marked as done in the registry after first execution.
=> [BUGFIX] Respect repeatable wizards and don't mark them as done

Resources/Private/ExtensionArtifacts/Classes/Console/Hook/ExtensionInstallation.php, Resources/Private/ExtensionArtifacts/ext_emconf.php
With the new extension build process we can avoid
such overhead, which can also lead to issues on updating
the extension
=> [BUGFIX] Avoid class map of all classes in non composer mode

Classes/Compatibility/CompatibilityClassLoader.php
Especially for TYPO3 version lower than 9.5 it is important
that the libraries shipped with the extension are used
instead of the ones shipped with TYPO3.
Fixes: #826
=> [BUGFIX] Ensure extension classloader has precedence

Classes/Console/Service/XsdGenerator.php
If you want to genereate an xsd file for the fluid viewhelpers it misses the splitted viewhelpers in TYPO3Fluid
=> [BUGFIX] Get proper project path for composer projects

Classes/Console/Core/Booting/Scripts.php, Classes/Console/Error/ErrorHandler.php, Classes/Console/Error/ExceptionRenderer.php, Classes/Console/Mvc/Cli/CommandConfiguration.php
Previously we ignored all TYPO3 configuration regarding
error and exception handling, to get a more reliable behavior
and a decent error output.
With this change we loosen this strictness a bit and at least look
at the configured error levels that should be logged or turned
into exceptions, but still enforce a reasonable configuration, by not
allowing warnings to be omitted.
Additionally we make sure both exceptions and errors are properly logged
using the logging framework.
We still disallow changing the error and exception handler to disallow
misconfiguration and also still not log errors to the legacy database log.
In case the latter is needed, it would still be possible to create a writer,
that writes to the database in a way that the TYPO3 backend log module
can use it.
=> [BUGFIX] Improve error and exception handling

Classes/Console/Command/Scheduler/RunCommand.php, Classes/Console/Command/Scheduler/SchedulerRunCommand.php, Configuration/Commands.php
The scheduler:run command is migrated from a CommandController
structure to a Symfony Command while keeping all existing
options as they are (including deprecated --task-id option).
=> [TASK] Migrate scheduler:run Command to Symfony Command

Classes/Console/Command/Frontend/FrontendRequestCommand.php, Classes/Console/Command/Frontend/RequestCommand.php, Configuration/Commands.php, Documentation/CommandReference/Index.rst, Tests/Console/Unit/Command/Frontend/RequestCommandTest.php
The following command is migrated from a CommandController structure to a Symfony Command:
- frontend:request
=> [TASK] Migrate FrontendCommandController to Symfony Commands

Classes/Console/Command/Install/InstallGeneratePackageStatesCommand.php, Classes/Console/Package/UncachedPackageManager.php
When generating PackageStates.php file, we now allow
DependencyOrderingService to be XCLASSed to be in line
with current TYPO3 behavior.
Fixes: #804
=> [BUGFIX] Allow XCLASS of DependencyOrderingService

Classes/Console/Command/Database/DatabaseUpdateSchemaCommand.php, Tests/Console/Functional/Command/DatabaseCommandControllerTest.php
Converting from command controller introduced a regression
that multiple schema types separated by comma were not properly
expanded to an array.
Fixes: #864
=> [BUGFIX] Allow specifying multiple schema update types

Classes/Console/Command/Upgrade/UpgradeCheckExtensionCompatibilityCommand.php
config-only input option of upgrade:checkextensioncompatibility command has wrong name, breaking other scripts such as  upgrade:all
=> Fixed naming of config-only input option

Classes/Console/Command/Install/InstallSetupCommand.php
The FIX resolves the problem, when a user is calling the command with the deprectated --non-interactive flag.
The deprecation warning leads to an unhandled Exception.
Call to undefined method Helhum\Typo3Console\Command\Install\InstallSetupCommand::writeln()
=> [BUGFIX] Use correct reference to call writeln() method

Classes/Console/Command/Upgrade/UpgradeAllCommand.php, Classes/Console/Command/Upgrade/UpgradeWizardCommand.php
I currently run into a problem with arguments for upgrade wizard command:
```bash
php typo3cms upgrade:wizard --no-interaction realurlAliasNewsSlug --arguments realurlAliasNewsSlug[install]=1
```
But this throws an exception:
```text
[ TypeError ]                                                                                                                                                            
Argument 2 passed to Helhum\Typo3Console\Install\Upgrade\UpgradeHandling::executeWizard() must be of the type array, string given, called in /var/www/html/htdocs/typo3  
conf/ext/typo3_console/Libraries/helhum/typo3-console/Classes/Console/Command/Upgrade/UpgradeSubProcessCommand.php on line 53
```
I think the input option mode should be set as an array.
When i change the mode to …
=> [BUGFIX] Set input option mode to array for upgrade wizard commands

Classes/Console/Parser/PhpParser.php, Tests/Console/Unit/Parser/PhpParserTest.php
Declaring a view helper as final didn't recognized
it when generating an XSD.
=> [BUGFIX] Allow final view helper classes in XSD generation

Classes/Console/Command/Upgrade/UpgradeCheckExtensionConstraintsCommand.php, Classes/Console/Error/ExceptionRenderer.php, Classes/Console/Mvc/Cli/SubProcessException.php, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php, appveyor.yml, composer.json
We can improve the rendering of SubProcessException
in other contexts as our own renderer, by setting the
line, code and trace accordingly.
Also fix our renderer if used outside TYPO3 context.
=> [BUGFIX] Fix rendering of SubProcessException

Classes/Console/Command/Cache/CacheFlushGroupsCommand.php, Classes/Console/Command/Cache/CacheFlushTagsCommand.php, Classes/Console/Command/Configuration/ConfigurationRemoveCommand.php, Classes/Console/Command/Configuration/ConfigurationSetCommand.php, Classes/Console/Command/Configuration/ConfigurationShowActiveCommand.php, Classes/Console/Command/Configuration/ConfigurationShowCommand.php, Classes/Console/Command/Configuration/ConfigurationShowLocalCommand.php, Classes/Console/Command/Database/DatabaseExportCommand.php, Classes/Console/Command/Database/DatabaseImportCommand.php, Classes/Console/Command/Database/DatabaseUpdateSchemaCommand.php, Classes/Console/Command/Install/InstallGeneratePackageStatesCommand.php, Documentation/CommandReference/CacheFlushgroups.rst, Documentation/CommandReference/CacheFlushtags.rst, Documentation/CommandReference/ConfigurationRemove.rst, Documentation/CommandReference/ConfigurationSet.rst, Documentation/CommandReference/ConfigurationShow.rst, Documentation/CommandReference/ConfigurationShowactive.rst, Documentation/CommandReference/ConfigurationShowlocal.rst, Documentation/CommandReference/DatabaseExport.rst, Documentation/CommandReference/DatabaseImport.rst, Documentation/CommandReference/DatabaseUpdateschema.rst, Documentation/CommandReference/InstallGeneratepackagestates.rst
This patch streamlines the command help descriptions according to the Symfony
command styling.
=> [TASK] Apply Symfony command styling

Classes/Console/Error/ExceptionRenderer.php, Classes/Console/Mvc/Cli/SubProcessException.php, Tests/Console/Unit/Error/ExceptionRendererTest.php, Tests/Console/Unit/Mvc/Cli/SubProcessExceptionTest.php
Exception codes can be string (e.g. for PDOException),
thus we must not assume codes are always integer.
=> [BUGFIX] Handle string Exception codes correctly

.travis.yml, Classes/Console/Install/Action/InteractiveActionArguments.php, Classes/Console/Install/Action/Typo3InstallAction.php, Configuration/Install/InstallSteps.yaml, Resources/Private/ExtensionArtifacts/composer.json, composer.json
It doesn't make sense to populate database credentials when sqlite
driver is chosen or site url, when no site is set up.
Therefore add conditions which are evaluated using Symfony
expression language.
=> [FEATURE] Add option to conditional skip individual setup arguments

Classes/Console/Core/Booting/Scripts.php
Since there might be some code accessing the global,
we need to still initialize it.
Fixes #907
=> [BUGFIX] Initialize LANG global during boot

Classes/Console/Command/Cache/CacheFlushCommand.php, Classes/Console/Service/CacheLowLevelCleaner.php, Classes/Console/Service/CacheService.php
Make use of TYPO3 API to flush caches when possible.
Only use our own API for file cache flushing.
=> [TASK] Clean up cache:flush command

Classes/Console/Composer/InstallerScript/PopulateCommandConfiguration.php
Since we removed scanning for extensions on runtime,
we must include them during Composer build time.
=> [BUGFIX] Include TYPO3 Extensions as command providers

Classes/Console/Command/Upgrade/UpgradeRunCommand.php, Documentation/CommandReference/UpgradeRun.rst, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php
Allow to use "--deny all" with a positive list of confirmations,
as well as "--confirm all" with a negative list of denials,
because depending on which amount of which kind of confirmable
wizards are available the one or the other might be
more convenient.
Resolves #913
=> [FEATURE] Handle positive list for upgrade wizard confirmations

Classes/Console/Command/Database/DatabaseExportCommand.php, Classes/Console/Command/Install/InstallGeneratePackageStatesCommand.php, Classes/Console/Composer/InstallerScript/PopulateCommandConfiguration.php, Classes/Console/Composer/InstallerScripts.php, Classes/Console/Composer/Util/PackageSorter.php, Classes/Console/Install/PackageStatesGenerator.php, Classes/Console/Service/CacheLowLevelCleaner.php, Documentation/CommandReference/InstallGeneratepackagestates.rst, Packages/CreateReferenceCommand/src/Command/CommandReferenceRenderCommand.php, Tests/Console/Unit/Install/PackageStatesGeneratorTest.php, composer.json
Since TYPO3 9.5 there is no possibility to use the
typo3/cms mono repo for Composer installations.
Therefore we must not compile the list of to be activated
framework extensions based on the required packages any more,
because only required framework extensions will be installed
anyway. Therefore we can just activate all framework extensions
that are found in Composer mode.
Since compiling this list was the remaining purpose of the plugin,
we can remove the dependency now.
=> Remove dependency to Composer plugin helper

Classes/Console/Command/Install/InstallExtensionSetupIfPossibleCommand.php, Classes/Console/Core/Booting/RunLevel.php, Documentation/CommandReference/InstallExtensionsetupifpossible.rst
This command is a wrapper to execute:
database:updateschema
cache:flush
extension:setupactive
Initially this was meant to be used in Composer scripts to
not interfere Composer install on build systems, but at the same
time perform necessary steps in dev systems.
It was, until now, not suitable for deployment scenarios though,
because during a deployment it is important that the command fails
when something goes wrong to avoid a broken state after a deployment.
The added option makes it now suitable for deployments, too.
Fixes: #925
=> [TASK] Add option to fail on error to extensionsetupifpossible

Classes/Console/Command/Database/DatabaseUpdateSchemaCommand.php, Classes/Console/Command/Extension/ExtensionStateCommandsHelper.php, Classes/Console/Extension/DatabaseSchemaUpdateEvent.php, Classes/Console/Extension/ExtensionSetup.php, Classes/Console/Extension/ExtensionSetupEventDispatcher.php, Classes/Console/Extension/ExtensionSetupResultRenderer.php, Classes/Console/Service/Database/SchemaService.php
Instead of calling protected methods, now public
API is called instead.
Also usage signal slot dispatcher is replaced
with even dispatcher API to properly collect
results from the process.
=> [BUGFIX] Use TYPO3 public extension setup API

Classes/Console/Core/Booting/ContainerBuildFailedException.php, Classes/Console/Core/Booting/RunLevel.php, Classes/Console/Core/Kernel.php, Classes/Console/Mvc/Cli/Symfony/Application.php
Low level commands don't need the full Symfony DI container,
thus we can gracefully execute them without showing errors
or even throw exceptions related to building this container.
Fixes #930
=> [BUGFIX] Hide container errors for low level commands

Classes/Console/Service/CacheLowLevelCleaner.php
- Recreate only if it was a directory. Otherwise files in the cache directory will be rewritten to directories
=> [BUGFIX] Recreation after cache:flush command

Classes/Console/Mvc/Cli/CommandDispatcher.php
Changed `&&` in the condition to `||`.
- If `$_SERVER['argv'][0]` is not set, throw exception
- If `$_SERVER['argv'][0]` is set, but does not contain the correct context, throw exception
Otherwise continue.
=> [BUGFIX] Wrong context RuntimeException is never reached without context

Classes/Console/Mvc/Cli/Symfony/Command/HelpCommand.php, Classes/Console/Mvc/Cli/Symfony/Command/ListCommand.php, Documentation/CommandReference/Help.rst, Documentation/CommandReference/List.rst
New SF Console versions changed the help text of list and help
commands. Since this text is rendered in the command reference,
and compatiblity with older console versions must be kept,
the help text od these commands is now copied to the
sublcasses used here.
=> [BUGFIX] Stay consistent with new Symfony Console versions

.travis.yml, Classes/Console/Install/Upgrade/UpgradeHandling.php
The confirmation messages of TYPO3's upgrade wizards are
a bit inconsistent and sometimes don't mention the action
that is to be confirmed at all.
Therefore output the wizard's title to clarify in which
context the confirmation is requested.
=> [BUGFIX] Output wizard title before asking for confirmation

Classes/Console/Database/Process/MysqlCommand.php
This PR applies to your `latest`-branch, other PRs for your other active branches follow.
Issue: Database-credentials are not properly escaped when writing the `--defaults-extra-file`. Usernames or passwords with backslashes (\\) and double-quotes (") won't work.
Solution: use `addslashes()` to escape username and password.
- @see https://dev.mysql.com/doc/refman/5.7/en/option-files.html
- @see https://dev.mysql.com/doc/refman/8.0/en/option-files.html
> Leading and trailing spaces are automatically deleted from option names and values.
>
> You can use the escape sequences \b, \t, \n, \r, \\\\, and \s in option values to represent the backspace, tab, newline, carriage return, backslash, and space characters. In option files, these escaping rules apply:
>
> A backslash followed by a valid …
=> [BUGFIX] escape database-username and -password in options-file created by mysql-command (branch latest)

Classes/Console/Core/Booting/Scripts.php
In TYPO3 v11 (master) the cache in IconRegistry is
injected via DI and the method "setCache" has been
removed. After this change, the code only calls 
"setCache" if available.
(I don't know how the versioning/release strategy is for 
console, this change is following the core master change 
because I stumbled upon it by accident - if you don't need it yet,
feel free to just close this again).
=> [TASK] Call setCache only if it exists

Classes/Console/Database/Process/MysqlCommand.php
The created file contains all credential for the current TYPO3
installation and these must not be overridden by potentially available
config files in the home directory of the current user.
Fixes #978
=> [BUGFIX] Make database:export use credentials in provided file

composer.json
Code dependency was removed quite some time ago,
so we can remove the Composer dependency as well
=> Remove dependency to doctrine/annotations

Resources/Private/ExtensionArtifacts/ext_emconf.php, composer.json
There is no dbal version compatible with TYPO3 10 or 11,
so we can safly remove the conflict now.
=> Remove conflict to dbal package

Classes/Console/Install/Action/Typo3InstallAction.php, Classes/Console/Install/InstallStepResponse.php
Only allow InstallStepRepsonse unserialisation
and throw an exception with a specific error message
in case this fails.
This will also ease error hunting in case installation process fails.
=> [TASK] Harden install action execution

Classes/Console/Service/Configuration/ConsoleRenderer/DiffConsoleRenderer.php, Tests/Console/Functional/Command/ConfigurationCommandControllerTest.php
When trying to get the MAIL configuration by entering the command
`typo3cms configuration:show MAIL`
I get the following error message:
`Fatal error: Declaration of Helhum\Typo3Console\Service\Configuration\ConsoleRenderer\DiffConsoleRenderer::callback($opcode, $from, $from_offset, $from_len) must be compatible with cogpowered\FineDiff\Render\RendererInterface::callback(string $opcode, string $from, int $from_offset, int $from_len): string in /var/www/vendor/helhum/typo3-console/Classes/Console/Service/Configuration/ConsoleRenderer/DiffConsoleRenderer.php on line 24`
This commit solves the issue by adding the appropriate type hints.
I am using TYPO3 v. 11.5.3 and the latest version of the console (7.0.4).
=> [BUGFIX] Add type hints to callback implementation

Classes/Console/Mvc/Cli/CommandDispatcher.php
As composer from 2.3.0 uses a newer symfony/console version the api
change kicks in. So just use the old api call for older composer versions.
Fixes #1042
=> [BUGFIX] Fix auto commands in composer environment

Classes/Console/Mvc/Cli/CommandDispatcher.php
Instead of relying on env vars with a version
being set, find out via reflection on runtime
how to properly construct a Process class
=> [TASK] Harden code for sub processes

Classes/Console/Command/Upgrade/UpgradeCheckExtensionConstraintsCommand.php, Classes/Console/Extension/ExtensionCompatibilityCheck.php, Classes/Console/Extension/ExtensionConstraintCheck.php, Classes/Console/Install/Upgrade/UpgradeHandling.php, Tests/Console/Functional/Command/UpgradeCommandControllerTest.php
When TYPO3 and extensions are installed with Composer, it is pointless
to check for ext_emconf.php files and version constraints in them,
because they are not evaluated any more since TYPO3 11.5.
Therefore, even if those files contain outdated information,
those have no effect on the installation and as such should
not lead to any errors.
Also fix upgrade:prepare to not deactivate an extension, as this
leads to errors, as packages can not be deactivated in Composer
mode during runtime any more
Fixes #1040
=> [BUGFIX] Disable extension constraint checks in Composer mode

Classes/Console/Mvc/Cli/CommandDispatcher.php
When Composer is compiled to phar, the comments are stripped,
so a fallback is needed and parameters are counted in that
case instead.
Fixes #1054
=> [BUGFIX] Correctly detect old process version

Classes/Console/Command/Upgrade/UpgradeRunCommand.php
With the change https://github.com/symfony/symfony/pull/46264 it's not
longer possible to provide a default value for required arguments and
the TYPO3 Console stops working with Symfony 6.0.9, 5.4.9 and 4.4.42.
=> Remove default value for required arguments

composer.json
Time has passed, so users will likely not run
into issues with these outdated packages any more.
=> Remove conflicts

Classes/Console/Error/ExceptionRenderer.php, Classes/Console/Mvc/Cli/Symfony/Descriptor/TextDescriptor.php, Classes/Console/SymfonyCompatibilityBridge.php, composer.json
TYPO3 v11 supports Symfony 5.0 - 5.4 while TYPO3 v12
requires Symfony 6.x.
For this reason, support for Symfony 4 within TYPO3 Console
is removed, which was impossible before anyways.
In addition, Symfony 6 support is added.
For `Symfony\Console\Helper\Helper::width()` a
compatibility layer is added to support both Symfony 5.0
and Symfony 6.x.
=> [TASK] Drop support for Symfony 4 + add Symfony 6 support

Classes/Compatibility/CompatibilityClassLoader.php
Accessing the property closure directly throws an exception:
```
> typo3cms install:generatepackagestates
[ Error ]                                                                    
Call to undefined method Helhum\Typo3Console\CompatibilityClassLoader::includeFile()                                                                    
Exception trace:
#0 ()
app/vendor/helhum/typo3-console/Classes/Compatibility/CompatibilityClassLoader.php:66
#1 Helhum\Typo3Console\CompatibilityClassLoader->loadClass()
#2 spl_autoload_call()
app/vendor/helhum/typo3-console/Classes/Console/Core/Kernel.php:94
#3 Helhum\Typo3Console\Core\Kernel->handle()
app/vendor/helhum/typo3-console/Scripts/typo3-console.php:31
#4 {closure}()
app/vendor/helhum/typo3-console/Scripts/typo3-console.php:33
#5 require() …
```
=> [BUGFIX] Access class property closure correctly

Classes/Console/Error/ErrorHandler.php, composer.json
Instead of only having nice error exceptions for warnings,
now all other errors are converted into an exception
with the help of a recently published package.
=> [BUGFIX] Log all errors the same way

Classes/Console/Command/Backend/CreateBackendAdminUserCommand.php, Classes/Console/Core/Booting/Scripts.php
This change adds basic functionality for TYPO3 v12.
By using TYPO3 v12 the main issue is providing
compatibility with symfony 6.
This means, that all *Command->execute() methods
need the return type "int" added. Similar
logic applies to "isHidden(): bool".
In addition, various helper functions need
to have their return type added.
The "Helper::strlen()" was deprecated in Symfony 5.3 and removed in Symfony 6. The replacement is
"Helper::width()" which is solved by using
a helper class to support both Symfony 4+6.
Support for TYPO3 v12 was provided by using
"Typo3Version" with a few switches regarding
Doctrine DBAL 3.x support and Bootstrap
(PageRenderer::setCache is not needed anymore).
Manual tests executed with TYPO3 v12:
* install:setup
* backend:createadmin
* upgrade:prepare
=> [DRAFT][TASK] Provide compatibility with TYPO3 v12

.github/workflows/Analyze.yml, .github/workflows/Deploy.yml, .github/workflows/Test.yml, .github/workflows/Update.yml
The following changes are done:
* Update deprecated actions
* Replace deprecated commands
* Update deprecated runner for tests
The remaining notices are generated by actions and will be fixed automatically on new action releases.
The new procedure to provide output from a job is currently not supported in PowerShell and therefor Bash is now also used on Windows. See also https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Fix deprecation notices in actions

.github/CONTRIBUTING.md, .github/workflows/Analyze.yml, .github/workflows/Test.yml, .gitignore, .php-cs-fixer.php, .styleci.yml, Classes/Console/Composer/InstallerScript/PopulateCommandConfiguration.php, Scripts/typo3-console.php, Tests/Console/Functional/Command/AbstractCommandTest.php, composer.json, sonar-project.properties
TYPO3 12 and 11 with composer installers 4
use a different directory layout, which needs to be respected
for the test setup
=> [TASK] Use new project directory layout

Resources/Private/ExtensionArtifacts/composer.json, composer.json
TYPO3 Console should never be installed in a
typo3conf/ext folder, thus new versions composer installers are required
=> !!![BUGFIX] Require current versions of composer installers

Classes/Compatibility/Typo3CompatibilityBridge.php, Classes/Console/Command/Configuration/ConfigurationRemoveCommand.php, Classes/Console/Command/Configuration/ConfigurationShowCommand.php, Classes/Console/Command/Configuration/ConfigurationShowLocalCommand.php, Classes/Console/Command/Install/InstallSetupCommand.php, Classes/Console/Install/Action/PrepareInstallAction.php, Classes/Console/Install/Upgrade/SilentConfigurationUpgrade.php, Classes/Console/Mvc/Cli/Symfony/Application.php, Classes/Console/Service/Configuration/ConfigurationService.php, Classes/Console/Service/Configuration/ConsoleRenderer/ConsoleRenderer.php, Documentation/CommandReference/ConfigurationRemove.rst, Documentation/CommandReference/ConfigurationShow.rst, Documentation/CommandReference/ConfigurationShowlocal.rst, Documentation/CommandReference/InstallSetup.rst, Tests/Console/Functional/Command/ConfigurationCommandControllerTest.php, Tests/Console/Functional/Command/Install/InstallCommandControllerTest.php
TYPO3 12 stores system configuration in a different location
AND introduced new API for the new file(s)
=> [TASK] Abstract access to system config file

.gitattributes, README.md
Since version v8.0.0 the previous available typo3cms is removed and this should be hinted in the readme.
Resolves: #1123
=> Change readme to reflect late changes.

Classes/Console/Database/Process/MysqlCommand.php
Simple check to add ssl flag into connection arguments.
relates to #1141
=> [FEATURE] Basic MySQL SSL support for database import and export command

Configuration/Install/InstallSteps.yaml, Tests/Console/Functional/Fixtures/Install/mysql-install.yaml, Tests/Console/Functional/Fixtures/Install/sqlite-install.yaml
`\Helhum\Typo3Console\Install\Action\InteractiveActionArguments::populate` loops over the argument definitions of the install step by name. The input options from the `install:setup` command define `--site-base-url`, which is translated to the givenArguments key `siteBaseUrl`.
Passing a base URL other than `/` to `--site-base-url` did not work at all, because the code looked for a `siteUrl` option instead.
=> Use siteBaseUrl instead of siteUrl for install step argument definition

.github/workflows/Test.yml
Testing against this TYPO3 branch at this point in time
is pointless, as too many things are broken. These
tests will be enabled, once working on compatibility with TYPO3 13
=> [TASK] Disable tests agains TYPO3 dev-main for now

README.md
This extension already supports TYPO3 12LTS. Let's announce this in the README.
=> [TASK] Add a 12LTS badge to the README

.php-cs-fixer.php, Classes/Console/Database/Configuration/ConnectionConfiguration.php, Classes/Console/Database/Process/MysqlCommand.php, Classes/Console/Database/Schema/SchemaUpdate.php, Classes/Console/Error/ExceptionRenderer.php, Classes/Console/Install/Action/InstallActionDispatcher.php, Classes/Console/Install/InstallStepActionExecutor.php, Classes/Console/Install/StepsConfig.php, Classes/Console/Install/Upgrade/SilentConfigurationUpgrade.php, Classes/Console/Install/Upgrade/UpgradeHandling.php, Classes/Console/Install/Upgrade/UpgradeWizardExecutor.php, Classes/Console/Install/Upgrade/UpgradeWizardFactory.php, Classes/Console/Install/Upgrade/UpgradeWizardList.php, Classes/Console/Mvc/Cli/CommandDispatcher.php, Classes/Console/Mvc/Cli/ConsoleOutput.php, Classes/Console/Mvc/Cli/Symfony/Input/ArgvInput.php, Classes/Console/Mvc/Cli/Symfony/Output/TrackableOutput.php, Classes/Console/Service/CacheService.php, Classes/Console/Service/Configuration/ConfigurationService.php, Tests/Console/Functional/Command/AbstractCommandTest.php, Tests/Console/Functional/Fixtures/Extensions/ext_command/src/ExtAlias.php, Tests/Console/Functional/Fixtures/Extensions/ext_command/src/ExtCommand.php, Tests/Console/Unit/Command/Frontend/RequestCommandTest.php
Since PHP 8.4 [implicitly nullable parameter declarations are deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated). Therefore, this PR enables the new `nullable_type_declaration_for_default_null_value` configuration option and converts all implicitly nullable parameter declarations to explicit type declarations.
=> [BUGFIX] Avoid implicitly nullable parameter declarations

.php-cs-fixer.php, composer.json
This PR migrates the following deprecated PHP-CS-Fixer rules (extracted from `vendor/bin/php-cs-fixer check -v`):
```
- Rule "function_typehint_space" is deprecated. Use "type_declaration_spaces" instead.
- Rule "new_with_braces" is deprecated. Use "new_with_parentheses" instead.
- Rule "no_blank_lines_before_namespace" is deprecated. Use "blank_lines_before_namespace" instead.
- Rule "no_trailing_comma_in_list_call" is deprecated. Use "no_trailing_comma_in_singleline" instead.
- Rule "no_trailing_comma_in_singleline_array" is deprecated. Use "no_trailing_comma_in_singleline" instead.
```
=> [TASK] Migrate deprecated PHP-CS-Fixer rules

composer.json
The last usage of this package were removed when the "typo3cms" CLI binary was dropped.
Notice that this dependency is kept for development since we invoke the TYPO3 "extension:setup" command for installation which looks up the "extension:dumpclassloadinginformation" command provided by the "typo3/cms-extensionmanager" package.
Fixes #1186
=> Drop typo3/cms-extensionmanager dependency
